/* ============================================================
   QUESTION POOL — large bank for random per-user test sets
   ------------------------------------------------------------
   Each item: { id, topic, level, q, opts: [4], ans: 0..3 }
   topic:  "HTML" | "CSS" | "JS" | "PY"
   level:  "easy" | "medium" | "hard"
   ------------------------------------------------------------
   To add more questions, append to the relevant array.
   IDs only need to be unique within their topic array.
   ============================================================ */

const POOL = {

// ============================================================
// HTML  (target: 80+ questions)
// ============================================================
HTML: [
// -------- EASY --------
{id:1,topic:"HTML",level:"easy",q:"Which tag defines the largest heading?",opts:["<h6>","<head>","<h1>","<heading>"],ans:2},
{id:2,topic:"HTML",level:"easy",q:"Which tag is used for a paragraph?",opts:["<para>","<p>","<pg>","<text>"],ans:1},
{id:3,topic:"HTML",level:"easy",q:"Which tag inserts a line break?",opts:["<lb>","<break>","<br>","<newline>"],ans:2},
{id:4,topic:"HTML",level:"easy",q:"Which tag draws a horizontal rule?",opts:["<line>","<rule>","<hr>","<row>"],ans:2},
{id:5,topic:"HTML",level:"easy",q:"Which is the correct HTML5 doctype?",opts:["<!DOCTYPE HTML5>","<!DOCTYPE html>","<DOCTYPE html>","<html5>"],ans:1},
{id:6,topic:"HTML",level:"easy",q:"Which tag creates a hyperlink?",opts:["<link>","<a>","<href>","<url>"],ans:1},
{id:7,topic:"HTML",level:"easy",q:"Which attribute holds a link's URL?",opts:["src","href","link","url"],ans:1},
{id:8,topic:"HTML",level:"easy",q:"Which tag inserts an image?",opts:["<image>","<picture>","<img>","<src>"],ans:2},
{id:9,topic:"HTML",level:"easy",q:"Which attribute provides image alt-text?",opts:["title","alt","name","desc"],ans:1},
{id:10,topic:"HTML",level:"easy",q:"Which tag creates an unordered list?",opts:["<ol>","<ul>","<list>","<li>"],ans:1},
{id:11,topic:"HTML",level:"easy",q:"Which tag creates an ordered list?",opts:["<ul>","<ol>","<list>","<order>"],ans:1},
{id:12,topic:"HTML",level:"easy",q:"List items use which tag?",opts:["<item>","<li>","<lt>","<list-item>"],ans:1},
{id:13,topic:"HTML",level:"easy",q:"Which tag defines a table row?",opts:["<td>","<tr>","<row>","<th>"],ans:1},
{id:14,topic:"HTML",level:"easy",q:"Which tag defines a table cell?",opts:["<tc>","<td>","<cell>","<tr>"],ans:1},
{id:15,topic:"HTML",level:"easy",q:"Which tag defines a header cell?",opts:["<head>","<th>","<header>","<top>"],ans:1},
{id:16,topic:"HTML",level:"easy",q:"Which input type is for passwords?",opts:["secret","pwd","password","hidden"],ans:2},
{id:17,topic:"HTML",level:"easy",q:"Which tag creates a button?",opts:["<btn>","<button>","<input>","<click>"],ans:1},
{id:18,topic:"HTML",level:"easy",q:"Which tag groups form fields?",opts:["<form>","<group>","<fields>","<panel>"],ans:0},
{id:19,topic:"HTML",level:"easy",q:"Default file extension for HTML?",opts:[".htm",".html","Both .htm and .html",".ht"],ans:2},
{id:20,topic:"HTML",level:"easy",q:"Which tag is for italic text?",opts:["<i>","<italic>","<em>","Both <i> and <em>"],ans:3},
{id:21,topic:"HTML",level:"easy",q:"Which tag is for bold text?",opts:["<bold>","<b>","<strong>","Both <b> and <strong>"],ans:3},
{id:22,topic:"HTML",level:"easy",q:"Which is an inline element?",opts:["<div>","<p>","<span>","<section>"],ans:2},
{id:23,topic:"HTML",level:"easy",q:"Which is a block-level element?",opts:["<span>","<a>","<div>","<i>"],ans:2},
{id:24,topic:"HTML",level:"easy",q:"Which tag adds a comment?",opts:["// comment","<!-- comment -->","# comment","/* comment */"],ans:1},
{id:25,topic:"HTML",level:"easy",q:"Which tag defines page title (browser tab)?",opts:["<head>","<header>","<title>","<h1>"],ans:2},
{id:26,topic:"HTML",level:"easy",q:"Where does <title> tag belong?",opts:["<body>","<head>","<html>","<meta>"],ans:1},
{id:27,topic:"HTML",level:"easy",q:"Which attribute uniquely identifies an element?",opts:["class","name","id","key"],ans:2},
{id:28,topic:"HTML",level:"easy",q:"Which input type is for checkbox?",opts:["check","checkbox","tick","box"],ans:1},
{id:29,topic:"HTML",level:"easy",q:"Which input type is for selecting one of many?",opts:["select","option","radio","pick"],ans:2},
{id:30,topic:"HTML",level:"easy",q:"Which tag creates a dropdown list?",opts:["<dropdown>","<select>","<menu>","<list>"],ans:1},
// -------- MEDIUM --------
{id:31,topic:"HTML",level:"medium",q:"Which attribute merges columns in a table?",opts:["merge","colspan","span","columns"],ans:1},
{id:32,topic:"HTML",level:"medium",q:"Which attribute merges rows in a table?",opts:["rowspan","mergeRow","span","rows"],ans:0},
{id:33,topic:"HTML",level:"medium",q:"Default method of an HTML <form>?",opts:["POST","GET","PUT","SUBMIT"],ans:1},
{id:34,topic:"HTML",level:"medium",q:"Which attribute makes input required?",opts:["mandatory","needed","required","must"],ans:2},
{id:35,topic:"HTML",level:"medium",q:"Which attribute disables an input?",opts:["disable","disabled","off","readonly"],ans:1},
{id:36,topic:"HTML",level:"medium",q:"<input type='number'> restricts input to:",opts:["Any character","Only digits/numbers","Only positive numbers","Decimals only"],ans:1},
{id:37,topic:"HTML",level:"medium",q:"Which tag adds semantic page header?",opts:["<head>","<header>","<top>","<h1>"],ans:1},
{id:38,topic:"HTML",level:"medium",q:"Which tag is for the footer area?",opts:["<bottom>","<footer>","<end>","<foot>"],ans:1},
{id:39,topic:"HTML",level:"medium",q:"<nav> tag is used for:",opts:["Navigation links","Navigation buttons only","Sitemap","Sidebar"],ans:0},
{id:40,topic:"HTML",level:"medium",q:"Which tag represents independent self-contained content?",opts:["<section>","<article>","<aside>","<div>"],ans:1},
{id:41,topic:"HTML",level:"medium",q:"Which tag embeds another HTML page?",opts:["<embed>","<iframe>","<object>","<frame>"],ans:1},
{id:42,topic:"HTML",level:"medium",q:"Which tag embeds video?",opts:["<media>","<video>","<movie>","<film>"],ans:1},
{id:43,topic:"HTML",level:"medium",q:"Which attribute autoplays a video?",opts:["start","play","autoplay","onload"],ans:2},
{id:44,topic:"HTML",level:"medium",q:"Which input type is for date?",opts:["calendar","date","day","time"],ans:1},
{id:45,topic:"HTML",level:"medium",q:"Which input type is for email validation?",opts:["mail","email","text","emailaddr"],ans:1},
{id:46,topic:"HTML",level:"medium",q:"Which attribute sets default value of input?",opts:["default","val","value","initial"],ans:2},
{id:47,topic:"HTML",level:"medium",q:"What does <label for='X'> do?",opts:["Links to ID X","Links to class X","Sets text X","No effect"],ans:0},
{id:48,topic:"HTML",level:"medium",q:"Which is correct way to write a meta charset?",opts:['<meta charset="UTF-8">','<meta type="UTF-8">','<charset value="UTF-8">','<meta name="UTF-8">'],ans:0},
{id:49,topic:"HTML",level:"medium",q:"Which meta tag enables mobile responsive viewport?",opts:["<meta mobile>",'<meta name="viewport" content="width=device-width, initial-scale=1">',"<meta responsive>","<viewport>"],ans:1},
{id:50,topic:"HTML",level:"medium",q:"Which tag pre-formats text (keeps spacing)?",opts:["<format>","<pre>","<code>","<text>"],ans:1},
{id:51,topic:"HTML",level:"medium",q:"<code> tag is typically used for:",opts:["Page code","Inline code snippet","Hidden code","Comments"],ans:1},
{id:52,topic:"HTML",level:"medium",q:"Which tag links an external CSS file?",opts:["<style>","<css>",'<link rel="stylesheet" href="...">',"<import>"],ans:2},
{id:53,topic:"HTML",level:"medium",q:"Which tag adds JavaScript to a page?",opts:["<javascript>","<script>","<js>","<code>"],ans:1},
{id:54,topic:"HTML",level:"medium",q:"Which attribute opens link in new tab?",opts:["target='blank'","target='_blank'","newtab","tab='new'"],ans:1},
{id:55,topic:"HTML",level:"medium",q:"Which entity represents a non-breaking space?",opts:["&space;","&nbsp;","&ns;","&blank;"],ans:1},
{id:56,topic:"HTML",level:"medium",q:"Which entity is the less-than sign?",opts:["&lt;","&less;","&gt;","&min;"],ans:0},
{id:57,topic:"HTML",level:"medium",q:"Which tag groups related form controls?",opts:["<group>","<fieldset>","<form-group>","<panel>"],ans:1},
{id:58,topic:"HTML",level:"medium",q:"<legend> tag is used inside:",opts:["<form>","<fieldset>","<label>","<table>"],ans:1},
{id:59,topic:"HTML",level:"medium",q:"Which tag is used for the largest possible heading visually?",opts:["<h1>","<h6>","<big>","<heading>"],ans:0},
{id:60,topic:"HTML",level:"medium",q:"Which tag should wrap a logo image typically?",opts:["<header>","<nav>","<aside>","<div>"],ans:0},
// -------- HARD --------
{id:61,topic:"HTML",level:"hard",q:"Which attribute makes form submission via AJAX easier (skips reload)?",opts:["target='_self'","ajax='true'","none — prevent in JS with e.preventDefault()","async"],ans:2},
{id:62,topic:"HTML",level:"hard",q:"<picture> element is used for:",opts:["3D models","Art-direction / responsive images","Audio","Vector art"],ans:1},
{id:63,topic:"HTML",level:"hard",q:"What does <output> tag represent?",opts:["Result of a calculation","Output stream","Print preview","Console output"],ans:0},
{id:64,topic:"HTML",level:"hard",q:"What does the 'defer' script attribute do?",opts:["Delays script forever","Executes after HTML parsed","Executes asynchronously","Disables script"],ans:1},
{id:65,topic:"HTML",level:"hard",q:"Difference: async vs defer scripts:",opts:["No difference","async runs after parse, defer immediately","async runs immediately when loaded, defer after parse","Both run before parse"],ans:2},
{id:66,topic:"HTML",level:"hard",q:"What does <template> tag do?",opts:["Loads templates from server","Holds inert HTML cloneable via JS","Defines CSS template","Renders Markdown"],ans:1},
{id:67,topic:"HTML",level:"hard",q:"data-* attributes are used for:",opts:["CSS only","Custom data storage on elements","Database queries","Form data only"],ans:1},
{id:68,topic:"HTML",level:"hard",q:"Which is a void (self-closing) element?",opts:["<p>","<div>","<input>","<span>"],ans:2},
{id:69,topic:"HTML",level:"hard",q:"Which element creates a popover/dialog?",opts:["<popup>","<modal>","<dialog>","<window>"],ans:2},
{id:70,topic:"HTML",level:"hard",q:"What does the contenteditable='true' attribute do?",opts:["Makes element draggable","Lets user edit element's text","Toggles disabled","Hides element"],ans:1},
{id:71,topic:"HTML",level:"hard",q:"What does <noscript> tag do?",opts:["Loads script alternative","Shows fallback when JS is disabled","Disables JS","Loads minimal script"],ans:1},
{id:72,topic:"HTML",level:"hard",q:"Which tag wraps long quoted text?",opts:["<q>","<quote>","<blockquote>","<cite>"],ans:2},
{id:73,topic:"HTML",level:"hard",q:"What does <progress max='100' value='40'> show?",opts:["A 40% filled progress bar","A spinner","A counter","Text '40/100'"],ans:0},
{id:74,topic:"HTML",level:"hard",q:"Which tag is used for term definition lists?",opts:["<ul>","<ol>","<dl>","<def>"],ans:2},
{id:75,topic:"HTML",level:"hard",q:"What does <details>/<summary> create?",opts:["Tooltip","Expandable disclosure widget","Hidden text","Footnote"],ans:1},
{id:76,topic:"HTML",level:"hard",q:"What is ARIA used for?",opts:["Animation","Accessibility hints for assistive tech","Routing","Caching"],ans:1},
{id:77,topic:"HTML",level:"hard",q:"What does the 'sandbox' attribute on iframe do?",opts:["Adds shadow","Restricts iframe capabilities","Enables fullscreen","Adds border"],ans:1},
{id:78,topic:"HTML",level:"hard",q:"Which input type creates a colour picker?",opts:["picker","colour","color","palette"],ans:2},
{id:79,topic:"HTML",level:"hard",q:"What does the 'multiple' attribute on <select> do?",opts:["Allows duplicate options","Allows selecting multiple options","Repeats select","Makes it a checkbox group"],ans:1},
{id:80,topic:"HTML",level:"hard",q:"What is the role of <main> tag?",opts:["The main heading","Container for dominant page content","Footer block","Navigation"],ans:1}
],

// ============================================================
// CSS  (target: 80+ questions)
// ============================================================
CSS: [
// -------- EASY --------
{id:1,topic:"CSS",level:"easy",q:"Symbol for class selector?",opts:["#",".","*","@"],ans:1},
{id:2,topic:"CSS",level:"easy",q:"Symbol for id selector?",opts:[".","#","&","$"],ans:1},
{id:3,topic:"CSS",level:"easy",q:"Universal selector?",opts:["all","*","#","%"],ans:1},
{id:4,topic:"CSS",level:"easy",q:"Property to change text colour?",opts:["text-color","font-color","color","fgcolor"],ans:2},
{id:5,topic:"CSS",level:"easy",q:"Property for background colour?",opts:["bg-color","background-color","color","back-color"],ans:1},
{id:6,topic:"CSS",level:"easy",q:"Property to set font size?",opts:["text-size","font-size","size","font"],ans:1},
{id:7,topic:"CSS",level:"easy",q:"Property to make text bold?",opts:["font-weight","text-bold","bold","weight"],ans:0},
{id:8,topic:"CSS",level:"easy",q:"Property for italic text?",opts:["font-italic","text-style","font-style","italic"],ans:2},
{id:9,topic:"CSS",level:"easy",q:"Property to remove underline from link?",opts:["text-style:none","decoration:none","text-decoration:none","underline:none"],ans:2},
{id:10,topic:"CSS",level:"easy",q:"Property for outer space?",opts:["margin","padding","border","space"],ans:0},
{id:11,topic:"CSS",level:"easy",q:"Property for inner space (inside border)?",opts:["margin","padding","gap","space"],ans:1},
{id:12,topic:"CSS",level:"easy",q:"Property to set element width?",opts:["w","width","size","len"],ans:1},
{id:13,topic:"CSS",level:"easy",q:"Property to set height?",opts:["h","height","size","y"],ans:1},
{id:14,topic:"CSS",level:"easy",q:"Property for rounded corners?",opts:["corner-radius","border-radius","round","radius"],ans:1},
{id:15,topic:"CSS",level:"easy",q:"Property for shadow on box?",opts:["shadow","drop-shadow","box-shadow","outline-shadow"],ans:2},
{id:16,topic:"CSS",level:"easy",q:"Make text uppercase via CSS?",opts:["text-transform:upper","case:upper","text-transform:uppercase","upper:true"],ans:2},
{id:17,topic:"CSS",level:"easy",q:"Center text horizontally?",opts:["text-align:center","align:center","center:true","text-center"],ans:0},
{id:18,topic:"CSS",level:"easy",q:"Hide an element completely (removes from layout)?",opts:["visibility:hidden","display:none","opacity:0","hide:true"],ans:1},
{id:19,topic:"CSS",level:"easy",q:"Make element invisible but keep space?",opts:["display:none","visibility:hidden","opacity:0","Both visibility:hidden and opacity:0"],ans:3},
{id:20,topic:"CSS",level:"easy",q:"Comment syntax in CSS?",opts:["// comment","# comment","<!-- comment -->","/* comment */"],ans:3},
{id:21,topic:"CSS",level:"easy",q:"Default display of <div>?",opts:["inline","block","inline-block","flex"],ans:1},
{id:22,topic:"CSS",level:"easy",q:"Default display of <span>?",opts:["block","inline","none","flex"],ans:1},
{id:23,topic:"CSS",level:"easy",q:"Make text not wrap?",opts:["wrap:none","white-space:nowrap","nowrap:true","text-wrap:no"],ans:1},
{id:24,topic:"CSS",level:"easy",q:"Property to change cursor style?",opts:["mouse","cursor","pointer","style"],ans:1},
{id:25,topic:"CSS",level:"easy",q:"Make cursor a hand on hover?",opts:["cursor:hand","cursor:pointer","cursor:click","cursor:hover"],ans:1},
{id:26,topic:"CSS",level:"easy",q:"Property for line spacing?",opts:["spacing","line-height","row-height","gap"],ans:1},
{id:27,topic:"CSS",level:"easy",q:"Property for letter spacing?",opts:["letter-gap","letter-spacing","char-spacing","spacing"],ans:1},
{id:28,topic:"CSS",level:"easy",q:"Property for word spacing?",opts:["word-spacing","gap","space","spacing"],ans:0},
{id:29,topic:"CSS",level:"easy",q:"How to add CSS inside HTML <head>?",opts:["<style>...</style>","<css>...</css>","<script type='css'>","<link>"],ans:0},
{id:30,topic:"CSS",level:"easy",q:"How to link external CSS?",opts:["@import",'<link rel="stylesheet" href="x.css">','<css src="x.css">',"<style src='x.css'>"],ans:1},
// -------- MEDIUM --------
{id:31,topic:"CSS",level:"medium",q:"position:fixed places element relative to:",opts:["Parent","Document","Viewport","Nearest positioned ancestor"],ans:2},
{id:32,topic:"CSS",level:"medium",q:"position:absolute is relative to:",opts:["Viewport","Document","Parent always","Nearest positioned ancestor"],ans:3},
{id:33,topic:"CSS",level:"medium",q:"position:relative shifts element relative to:",opts:["Viewport","Parent","Its own normal position","Document"],ans:2},
{id:34,topic:"CSS",level:"medium",q:"position:sticky behaves like:",opts:["fixed always","relative until scroll threshold, then fixed","absolute","static"],ans:1},
{id:35,topic:"CSS",level:"medium",q:"display:flex makes a container:",opts:["Block","Inline","Flex layout (1D)","Grid layout"],ans:2},
{id:36,topic:"CSS",level:"medium",q:"Align items along main axis in flexbox?",opts:["align-items","justify-content","flex-direction","align-content"],ans:1},
{id:37,topic:"CSS",level:"medium",q:"Align items along cross axis in flexbox?",opts:["justify-content","align-items","flex-wrap","gap"],ans:1},
{id:38,topic:"CSS",level:"medium",q:"Default flex-direction?",opts:["column","row","row-reverse","column-reverse"],ans:1},
{id:39,topic:"CSS",level:"medium",q:"flex-wrap:wrap allows items to:",opts:["Stretch","Wrap onto next line","Shrink","Be ignored"],ans:1},
{id:40,topic:"CSS",level:"medium",q:"flex:1 on a child means:",opts:["Width 1px","Grow equally with siblings","Hide","Fix size to 1em"],ans:1},
{id:41,topic:"CSS",level:"medium",q:"display:grid creates:",opts:["Flex layout","1D layout","2D grid layout","Table"],ans:2},
{id:42,topic:"CSS",level:"medium",q:"grid-template-columns:1fr 2fr 1fr means:",opts:["3 equal cols","Cols 1/4, 2/4, 1/4 widths","px values","Errors"],ans:1},
{id:43,topic:"CSS",level:"medium",q:"@media (max-width:768px) targets:",opts:["Screens up to 768px","Screens above 768px","Print","Mobile only"],ans:0},
{id:44,topic:"CSS",level:"medium",q:"@keyframes is used for:",opts:["Transitions","Animations","Media queries","Variables"],ans:1},
{id:45,topic:"CSS",level:"medium",q:"transition property triggers when:",opts:["Page loads","CSS value changes","Hovered always","Manually"],ans:1},
{id:46,topic:"CSS",level:"medium",q:":hover pseudo-class fires when:",opts:["Click","Pointer over element","Focus","Always"],ans:1},
{id:47,topic:"CSS",level:"medium",q:":nth-child(2n) targets:",opts:["First two children","Every 2nd child (even)","Last 2 children","No children"],ans:1},
{id:48,topic:"CSS",level:"medium",q:":first-child applies when element is:",opts:["First child of its parent","Last child","Only child","Any child"],ans:0},
{id:49,topic:"CSS",level:"medium",q:"z-index controls:",opts:["Zoom","Stacking order","Z-axis perspective","Animation speed"],ans:1},
{id:50,topic:"CSS",level:"medium",q:"z-index works only on:",opts:["Any element","Positioned elements (non-static)","Block elements","Inline elements"],ans:1},
{id:51,topic:"CSS",level:"medium",q:"What does box-sizing:border-box do?",opts:["Width includes padding+border","Width excludes everything","Adds border","Removes padding"],ans:0},
{id:52,topic:"CSS",level:"medium",q:"Unit '1em' equals:",opts:["1px","Parent's font-size","Root font-size","16px always"],ans:1},
{id:53,topic:"CSS",level:"medium",q:"Unit '1rem' equals:",opts:["Parent's font-size","Root (html) font-size","16px always","1px"],ans:1},
{id:54,topic:"CSS",level:"medium",q:"Unit '1vh' equals:",opts:["1% of viewport width","1% of viewport height","1px","1em"],ans:1},
{id:55,topic:"CSS",level:"medium",q:"Property overflow:hidden does what?",opts:["Removes content","Clips overflowing content","Adds scrollbar","Hides element"],ans:1},
{id:56,topic:"CSS",level:"medium",q:"overflow:auto behaves how?",opts:["Always hides","Always scrolls","Scrolls only if needed","Shows everything"],ans:2},
{id:57,topic:"CSS",level:"medium",q:"How to write a CSS variable?",opts:["$x: 5px","var x = 5px","--x: 5px","@x: 5px"],ans:2},
{id:58,topic:"CSS",level:"medium",q:"How to use a CSS variable?",opts:["color: $x","color: var(--x)","color: @x","color: x"],ans:1},
{id:59,topic:"CSS",level:"medium",q:"Selector specificity highest among:",opts:["element","class","id","tag"],ans:2},
{id:60,topic:"CSS",level:"medium",q:"!important on a property:",opts:["Adds emphasis","Overrides normal specificity","Hides rule","Pre-loads it"],ans:1},
// -------- HARD --------
{id:61,topic:"CSS",level:"hard",q:"Difference between margin:auto vs text-align:center?",opts:["Same thing","margin centers block, text-align centers inline content","margin:auto only horizontal","Both b and c"],ans:3},
{id:62,topic:"CSS",level:"hard",q:"What does 'min-height: 100vh' on body achieve?",opts:["Caps height at viewport","Body fills at least the viewport height","No effect","100px"],ans:1},
{id:63,topic:"CSS",level:"hard",q:"Stacking context is created by:",opts:["Any element","Positioned elements with z-index, opacity<1, transform, etc.","Only z-index","Only display:flex"],ans:1},
{id:64,topic:"CSS",level:"hard",q:"transform:translate(50%,50%) moves element by:",opts:["50px","50% of viewport","50% of element's own size","50% of parent"],ans:2},
{id:65,topic:"CSS",level:"hard",q:"Difference: 'transition' vs 'animation'?",opts:["Same","transition needs state change; animation runs via @keyframes","animation is faster","transition can loop"],ans:1},
{id:66,topic:"CSS",level:"hard",q:"calc(100% - 20px) is valid?",opts:["No","Yes — supports math","Only in @media","Only in grid"],ans:1},
{id:67,topic:"CSS",level:"hard",q:"What is the BFC (Block Formatting Context)?",opts:["Browser font cache","Independent rendering area for blocks","Box layout class","Flex shorthand"],ans:1},
{id:68,topic:"CSS",level:"hard",q:"Which value clears floats?",opts:["clear:both","float:none","overflow:auto","Both clear:both and overflow:auto"],ans:3},
{id:69,topic:"CSS",level:"hard",q:"What does object-fit:cover do on <img>?",opts:["Stretches","Fills box, crops excess preserving aspect ratio","Shrinks","No effect"],ans:1},
{id:70,topic:"CSS",level:"hard",q:"Difference between rgba() and rgb()?",opts:["No difference","rgba includes alpha (opacity)","rgba uses percentages","rgb is deprecated"],ans:1},
{id:71,topic:"CSS",level:"hard",q:"opacity:0.5 affects:",opts:["Element only","Element AND all children","Children only","Background only"],ans:1},
{id:72,topic:"CSS",level:"hard",q:":not(.x) selector means:",opts:["Class x","All not having class x","Only x","Negates rule"],ans:1},
{id:73,topic:"CSS",level:"hard",q:"What is a CSS combinator '>'?",opts:["OR","Direct child selector","Sibling","Descendant"],ans:1},
{id:74,topic:"CSS",level:"hard",q:"What does '~' combinator select?",opts:["Direct sibling","All next siblings","Parent","Child"],ans:1},
{id:75,topic:"CSS",level:"hard",q:"What does '+' combinator select?",opts:["Sum of selectors","Immediate next sibling","Parent","All children"],ans:1},
{id:76,topic:"CSS",level:"hard",q:"In flexbox, align-self overrides:",opts:["justify-content","align-items for that one item","flex-direction","flex-wrap"],ans:1},
{id:77,topic:"CSS",level:"hard",q:"gap property works in:",opts:["flexbox only","grid only","Both flex and grid","Block only"],ans:2},
{id:78,topic:"CSS",level:"hard",q:"What does will-change property hint?",opts:["Hides element","Tells browser to prepare optimisations for animations","Triggers reflow","Disables animation"],ans:1},
{id:79,topic:"CSS",level:"hard",q:"What does aspect-ratio: 16/9 enforce?",opts:["Width 16, height 9 px","16:9 ratio between width and height","16% width","9px height"],ans:1},
{id:80,topic:"CSS",level:"hard",q:"What is a 'pseudo-element' example?",opts:[":hover","::before","[type=text]",":nth-child"],ans:1}
],

// ============================================================
// JavaScript  (target: 120+ questions)
// ============================================================
JS: [
// -------- EASY --------
{id:1,topic:"JS",level:"easy",q:"Which keyword declares a block-scoped variable?",opts:["var","let","const","Both let and const"],ans:3},
{id:2,topic:"JS",level:"easy",q:"Which keyword declares a constant?",opts:["var","const","let","fix"],ans:1},
{id:3,topic:"JS",level:"easy",q:"Which keyword has function-scope?",opts:["var","let","const","static"],ans:0},
{id:4,topic:"JS",level:"easy",q:"Which symbol is for arrow function?",opts:["->","=>","::",":>"],ans:1},
{id:5,topic:"JS",level:"easy",q:"How to print to console?",opts:["print()","echo()","console.log()","log()"],ans:2},
{id:6,topic:"JS",level:"easy",q:"How to comment a line?",opts:["# this","// this","-- this","<!-- this -->"],ans:1},
{id:7,topic:"JS",level:"easy",q:"How to write multi-line comment?",opts:["/* ... */","// ...","# ...","<!-- ... -->"],ans:0},
{id:8,topic:"JS",level:"easy",q:"typeof 'hello' returns?",opts:["text","string","str","object"],ans:1},
{id:9,topic:"JS",level:"easy",q:"typeof 42 returns?",opts:["int","number","numeric","integer"],ans:1},
{id:10,topic:"JS",level:"easy",q:"typeof true returns?",opts:["bool","boolean","truth","number"],ans:1},
{id:11,topic:"JS",level:"easy",q:"typeof null returns?",opts:["null","undefined","object","none"],ans:2},
{id:12,topic:"JS",level:"easy",q:"typeof undefined returns?",opts:["null","undefined","object","none"],ans:1},
{id:13,topic:"JS",level:"easy",q:"What does '+' do with two strings?",opts:["Adds numerically","Concatenates","Errors","Subtracts"],ans:1},
{id:14,topic:"JS",level:"easy",q:"'5' + 3 evaluates to?",opts:["8","53","'53'","NaN"],ans:2},
{id:15,topic:"JS",level:"easy",q:"'5' - 3 evaluates to?",opts:["'53'","2","NaN","Error"],ans:1},
{id:16,topic:"JS",level:"easy",q:"What is 10 % 3?",opts:["3","1","0","3.3"],ans:1},
{id:17,topic:"JS",level:"easy",q:"What is 2 ** 3?",opts:["6","8","9","23"],ans:1},
{id:18,topic:"JS",level:"easy",q:"=== checks?",opts:["Value only","Value and type","Type only","Loose equality"],ans:1},
{id:19,topic:"JS",level:"easy",q:"== checks?",opts:["Strict equality","Loose equality (with type coercion)","Reference","None"],ans:1},
{id:20,topic:"JS",level:"easy",q:"Method to select element by id?",opts:["getById","querySelector","getElementById","findById"],ans:2},
{id:21,topic:"JS",level:"easy",q:"querySelector('.x') selects?",opts:["All elements with class x","First element with class x","Element with id x","Tag x"],ans:1},
{id:22,topic:"JS",level:"easy",q:"querySelectorAll returns?",opts:["First match","NodeList of all matches","Array","String"],ans:1},
{id:23,topic:"JS",level:"easy",q:"Which event fires on button click?",opts:["onhover","onclick","onpress","onpush"],ans:1},
{id:24,topic:"JS",level:"easy",q:"How to add event listener?",opts:["addEvent","on()","addEventListener","attachEvent"],ans:2},
{id:25,topic:"JS",level:"easy",q:"innerHTML property gets/sets?",opts:["Tag name","HTML content inside element","Attribute","CSS"],ans:1},
{id:26,topic:"JS",level:"easy",q:"How to create a function?",opts:["function name() {}","def name():","func name {}","fn name()"],ans:0},
{id:27,topic:"JS",level:"easy",q:"How many elements does Array(3) create?",opts:["1","3 (empty slots)","0","Error"],ans:1},
{id:28,topic:"JS",level:"easy",q:"Method to add item to end of array?",opts:["add","push","append","insert"],ans:1},
{id:29,topic:"JS",level:"easy",q:"Method to remove last item of array?",opts:["pop","remove","del","shift"],ans:0},
{id:30,topic:"JS",level:"easy",q:"Method to remove first item of array?",opts:["pop","shift","first","remove"],ans:1},
{id:31,topic:"JS",level:"easy",q:"Method to add item at start of array?",opts:["push","unshift","insert","prepend"],ans:1},
{id:32,topic:"JS",level:"easy",q:"How to get array length?",opts:[".size",".length","len()","count()"],ans:1},
{id:33,topic:"JS",level:"easy",q:"What's the result: [1,2,3].length?",opts:["2","3","4","Error"],ans:1},
{id:34,topic:"JS",level:"easy",q:"How to declare an object?",opts:["{}","[]","new()","class()"],ans:0},
{id:35,topic:"JS",level:"easy",q:"How to access object property?",opts:["obj->key","obj.key","obj::key","obj#key"],ans:1},
{id:36,topic:"JS",level:"easy",q:"Which converts string to integer?",opts:["int()","Number()","parseInt()","Both Number() and parseInt()"],ans:3},
{id:37,topic:"JS",level:"easy",q:"Math.round(4.5) returns?",opts:["4","5","4.5","NaN"],ans:1},
{id:38,topic:"JS",level:"easy",q:"Math.floor(4.7) returns?",opts:["4","5","4.7","Error"],ans:0},
{id:39,topic:"JS",level:"easy",q:"Math.ceil(4.1) returns?",opts:["4","5","4.1","NaN"],ans:1},
{id:40,topic:"JS",level:"easy",q:"Math.random() returns number in:",opts:["[0, 1]","[0, 1)","[1, 10]","-1 to 1"],ans:1},
// -------- MEDIUM --------
{id:41,topic:"JS",level:"medium",q:"Result: typeof []?",opts:["array","object","list","undefined"],ans:1},
{id:42,topic:"JS",level:"medium",q:"Result: typeof function(){}",opts:["function","object","callable","undefined"],ans:0},
{id:43,topic:"JS",level:"medium",q:"Array.isArray([1,2,3]) returns?",opts:["true","false","null","[1,2,3]"],ans:0},
{id:44,topic:"JS",level:"medium",q:"What does .map() return?",opts:["Modifies original","New array of transformed items","Filtered array","Number"],ans:1},
{id:45,topic:"JS",level:"medium",q:"What does .filter() return?",opts:["Boolean","New array with items passing test","Modified original","Number"],ans:1},
{id:46,topic:"JS",level:"medium",q:"What does .reduce() return?",opts:["Array","Single accumulated value","Number","Object"],ans:1},
{id:47,topic:"JS",level:"medium",q:"What does .forEach() return?",opts:["New array","undefined","First item","Original array"],ans:1},
{id:48,topic:"JS",level:"medium",q:"What does .find() return?",opts:["All matches","First matching item","Array of matches","Boolean"],ans:1},
{id:49,topic:"JS",level:"medium",q:"What does .includes() return?",opts:["Index","Boolean","First match","All matches"],ans:1},
{id:50,topic:"JS",level:"medium",q:"What does .indexOf() return when not found?",opts:["0","-1","null","Error"],ans:1},
{id:51,topic:"JS",level:"medium",q:"Output: [1,2,3].map(x=>x*2)?",opts:["[1,2,3]","[2,4,6]","[1,4,9]","6"],ans:1},
{id:52,topic:"JS",level:"medium",q:"Output: [1,2,3,4].filter(x=>x%2)?",opts:["[2,4]","[1,3]","[1,2,3,4]","2"],ans:1},
{id:53,topic:"JS",level:"medium",q:"Output: [1,2,3].reduce((a,b)=>a+b,0)?",opts:["[6]","6","123","Error"],ans:1},
{id:54,topic:"JS",level:"medium",q:"How to convert object to JSON string?",opts:["obj.toJSON()","JSON.stringify(obj)","String(obj)","obj.toString()"],ans:1},
{id:55,topic:"JS",level:"medium",q:"How to parse JSON string to object?",opts:["JSON.parse(str)","parseJSON(str)","str.toObject()","Object(str)"],ans:0},
{id:56,topic:"JS",level:"medium",q:"What does fetch() return?",opts:["Response data","Promise resolving to Response","Synchronous result","String"],ans:1},
{id:57,topic:"JS",level:"medium",q:"How to handle fetch errors?",opts:["try-catch around await","Use .catch() on the promise","Check response.ok","All of the above"],ans:3},
{id:58,topic:"JS",level:"medium",q:"async function always returns?",opts:["A value","Undefined","A Promise","An object"],ans:2},
{id:59,topic:"JS",level:"medium",q:"What does await do?",opts:["Stops execution","Pauses until promise resolves","Errors","Skips line"],ans:1},
{id:60,topic:"JS",level:"medium",q:"setTimeout(fn, 1000) runs fn after?",opts:["1 second","1000 seconds","1 ms","Immediately"],ans:0},
{id:61,topic:"JS",level:"medium",q:"setInterval is for?",opts:["One-time delay","Repeated execution at interval","Delay forever","Cancel timer"],ans:1},
{id:62,topic:"JS",level:"medium",q:"clearTimeout(id) does?",opts:["Stops the timer","Resets","Runs it","Logs error"],ans:0},
{id:63,topic:"JS",level:"medium",q:"Template literals use which chars?",opts:["\"\"","''","``","[]"],ans:2},
{id:64,topic:"JS",level:"medium",q:"In `Hello ${name}`, what is ${name}?",opts:["String literal","Variable interpolation","Template tag","Comment"],ans:1},
{id:65,topic:"JS",level:"medium",q:"Spread operator syntax?",opts:["...","--",":::","spread()"],ans:0},
{id:66,topic:"JS",level:"medium",q:"What does [...arr1, ...arr2] do?",opts:["Errors","Merges into new array","Adds first to second","Removes duplicates"],ans:1},
{id:67,topic:"JS",level:"medium",q:"Destructuring: const {a,b} = obj — picks?",opts:["First two","Properties a and b","Array items","Errors"],ans:1},
{id:68,topic:"JS",level:"medium",q:"Default param: function f(x=5) — if called f()?",opts:["undefined","5","null","0"],ans:1},
{id:69,topic:"JS",level:"medium",q:"What's null == undefined?",opts:["true","false","Error","null"],ans:0},
{id:70,topic:"JS",level:"medium",q:"What's null === undefined?",opts:["true","false","Error","Both"],ans:1},
{id:71,topic:"JS",level:"medium",q:"Output: typeof NaN?",opts:["NaN","number","undefined","Error"],ans:1},
{id:72,topic:"JS",level:"medium",q:"Is NaN === NaN?",opts:["true","false","Error","Maybe"],ans:1},
{id:73,topic:"JS",level:"medium",q:"How to check NaN safely?",opts:["x===NaN","isNaN(x)","Number.isNaN(x)","Both isNaN(x) and Number.isNaN(x)"],ans:3},
{id:74,topic:"JS",level:"medium",q:"What is hoisting?",opts:["Moving HTML up","var/function declarations hoisted to top of scope","Lifting CSS","Cache"],ans:1},
{id:75,topic:"JS",level:"medium",q:"Are let/const hoisted?",opts:["No","Yes but in temporal dead zone","Same as var","Errors"],ans:1},
{id:76,topic:"JS",level:"medium",q:"What is a closure?",opts:["A loop","Function with access to outer scope","An object","An event"],ans:1},
{id:77,topic:"JS",level:"medium",q:"'this' inside arrow function refers to?",opts:["Window","Outer (lexical) scope's this","Function itself","Caller"],ans:1},
{id:78,topic:"JS",level:"medium",q:"What does Object.keys(obj) return?",opts:["Values","Array of keys","Length","Map"],ans:1},
{id:79,topic:"JS",level:"medium",q:"Object.values(obj) returns?",opts:["Keys","Array of values","Length","Pairs"],ans:1},
{id:80,topic:"JS",level:"medium",q:"Object.entries(obj) returns?",opts:["Keys","Values","Array of [key,value] pairs","Length"],ans:2},
{id:81,topic:"JS",level:"medium",q:"How to add property to object?",opts:["obj.x = 5","obj['x'] = 5","Object.assign","All of the above"],ans:3},
{id:82,topic:"JS",level:"medium",q:"How to delete object property?",opts:["delete obj.x","obj.x = null","remove(obj.x)","obj.delete('x')"],ans:0},
{id:83,topic:"JS",level:"medium",q:"What does Array.from(str) do (str='abc')?",opts:["['abc']","['a','b','c']","'abc'","Error"],ans:1},
{id:84,topic:"JS",level:"medium",q:"How to join array elements with comma?",opts:["arr.toString()","arr.join(',')","arr+','","Both toString and join"],ans:3},
{id:85,topic:"JS",level:"medium",q:"split('-') on 'a-b-c' returns?",opts:["'abc'","['a','b','c']","['a-b-c']","['a','-','b','-','c']"],ans:1},
{id:86,topic:"JS",level:"medium",q:"String method to lowercase?",opts:["small()","lower()","toLowerCase()","downCase()"],ans:2},
{id:87,topic:"JS",level:"medium",q:"String method to uppercase?",opts:["big()","upper()","toUpperCase()","cap()"],ans:2},
{id:88,topic:"JS",level:"medium",q:"String method for trimming whitespace?",opts:["strip()","trim()","clean()","cut()"],ans:1},
{id:89,topic:"JS",level:"medium",q:".slice(1,3) on 'hello' returns?",opts:["'he'","'el'","'ell'","'hell'"],ans:1},
{id:90,topic:"JS",level:"medium",q:".replace('a','b') replaces?",opts:["All a's","First a only","Last a","None"],ans:1},
{id:91,topic:"JS",level:"medium",q:".replaceAll('a','b') replaces?",opts:["First a","All a's","Last a","None"],ans:1},
// -------- HARD --------
{id:92,topic:"JS",level:"hard",q:"Output: console.log(0.1 + 0.2 === 0.3)?",opts:["true","false","0.3","Error"],ans:1},
{id:93,topic:"JS",level:"hard",q:"What is the event loop?",opts:["A for loop","Mechanism handling async callbacks","DOM event","CSS animation"],ans:1},
{id:94,topic:"JS",level:"hard",q:"Output: [1]+[2]?",opts:["[1,2]","'12'","3","[3]"],ans:1},
{id:95,topic:"JS",level:"hard",q:"Output: {}+[] in some browsers may be?",opts:["[object Object]","0","NaN","Error"],ans:1},
{id:96,topic:"JS",level:"hard",q:"Promise.all([p1,p2]) resolves when?",opts:["First resolves","All resolve (or one rejects)","Last resolves","Never"],ans:1},
{id:97,topic:"JS",level:"hard",q:"Promise.race resolves when?",opts:["All resolve","First settles (resolve or reject)","Last","Never"],ans:1},
{id:98,topic:"JS",level:"hard",q:"What is currying?",opts:["Sorting","Function transformation: f(a,b,c) → f(a)(b)(c)","Caching","Recursion"],ans:1},
{id:99,topic:"JS",level:"hard",q:"What does Object.freeze() do?",opts:["Deep clone","Prevents modifications to object (shallow)","Hides","Removes properties"],ans:1},
{id:100,topic:"JS",level:"hard",q:"What does Object.seal() do?",opts:["Locks values","Prevents add/delete props but allows modifying","Same as freeze","Hides"],ans:1},
{id:101,topic:"JS",level:"hard",q:"Difference: call vs apply?",opts:["No diff","call takes args separately, apply takes array","apply faster","apply for async"],ans:1},
{id:102,topic:"JS",level:"hard",q:"bind() returns?",opts:["Result","New function with bound this","Same function","undefined"],ans:1},
{id:103,topic:"JS",level:"hard",q:"What is a Symbol?",opts:["String","Unique primitive value","Object","Number"],ans:1},
{id:104,topic:"JS",level:"hard",q:"What does Object.create(null) make?",opts:["Empty array","Object with no prototype","null","Error"],ans:1},
{id:105,topic:"JS",level:"hard",q:"What's prototypal inheritance?",opts:["Class-based","Objects inherit via __proto__ chain","No inheritance","Through constructors only"],ans:1},
{id:106,topic:"JS",level:"hard",q:"class syntax in ES6 is?",opts:["Real class","Syntactic sugar over prototypes","New paradigm","Not supported"],ans:1},
{id:107,topic:"JS",level:"hard",q:"What is a generator function?",opts:["Random","Function that can pause via yield","Async","Recursive"],ans:1},
{id:108,topic:"JS",level:"hard",q:"What's localStorage limit (typical)?",opts:["1 KB","5–10 MB","Unlimited","1 MB"],ans:1},
{id:109,topic:"JS",level:"hard",q:"sessionStorage persists when?",opts:["Forever","Tab/window session","1 hour","Until reload"],ans:1},
{id:110,topic:"JS",level:"hard",q:"What is debouncing?",opts:["Delaying function calls until activity stops","Speeding up calls","Caching","Throttle"],ans:0},
{id:111,topic:"JS",level:"hard",q:"What is throttling?",opts:["Block calls","Limit function to run once per interval","Same as debounce","Cache"],ans:1},
{id:112,topic:"JS",level:"hard",q:"requestAnimationFrame is for?",opts:["Layout","Smooth animations synced with screen refresh","Loading","Network"],ans:1},
{id:113,topic:"JS",level:"hard",q:"Output: console.log(typeof typeof 1)?",opts:["number","string","object","undefined"],ans:1},
{id:114,topic:"JS",level:"hard",q:"Optional chaining ?.x does?",opts:["Errors if undefined","Returns undefined if before is null/undefined","Sets default","Same as &&"],ans:1},
{id:115,topic:"JS",level:"hard",q:"Nullish coalescing ?? returns right when left is?",opts:["false","0","null or undefined","Empty string"],ans:2},
{id:116,topic:"JS",level:"hard",q:"What's the difference: forEach vs for…of?",opts:["No diff","forEach skips break/continue, for…of supports them","for…of is async","forEach faster"],ans:1},
{id:117,topic:"JS",level:"hard",q:"Map vs Object: which keeps insertion order?",opts:["Object","Map","Both","Neither"],ans:1},
{id:118,topic:"JS",level:"hard",q:"Set holds?",opts:["Key-value","Unique values","Pairs","Arrays only"],ans:1},
{id:119,topic:"JS",level:"hard",q:"What does Symbol.iterator do?",opts:["Random","Defines how object is iterated","Sorts","Maps"],ans:1},
{id:120,topic:"JS",level:"hard",q:"What does Object.assign({}, a, b) do?",opts:["Compares","Merges enumerable props of a and b into {} (shallow)","Deep clone","Errors"],ans:1}
],

// ============================================================
// Python  (target: 150+ questions)
// ============================================================
PY: [
// -------- EASY --------
{id:1,topic:"PY",level:"easy",q:"Which function prints output?",opts:["echo()","display()","print()","output()"],ans:2},
{id:2,topic:"PY",level:"easy",q:"Which function reads input?",opts:["read()","scan()","input()","get()"],ans:2},
{id:3,topic:"PY",level:"easy",q:"Comment in Python starts with?",opts:["//","#","/*","--"],ans:1},
{id:4,topic:"PY",level:"easy",q:"Multi-line comment uses?",opts:["/* ... */","// ... //","Triple quotes \"\"\" ... \"\"\"","# ... #"],ans:2},
{id:5,topic:"PY",level:"easy",q:"Which keyword defines function?",opts:["function","def","func","define"],ans:1},
{id:6,topic:"PY",level:"easy",q:"Which keyword for class?",opts:["class","Class","def","struct"],ans:0},
{id:7,topic:"PY",level:"easy",q:"How to import a module?",opts:["import math","include math","using math","require math"],ans:0},
{id:8,topic:"PY",level:"easy",q:"Indentation in Python is?",opts:["Optional","Required","Use {}","Use ;"],ans:1},
{id:9,topic:"PY",level:"easy",q:"Standard indent in Python?",opts:["1 space","2 spaces","4 spaces","Tab only"],ans:2},
{id:10,topic:"PY",level:"easy",q:"How to create a list?",opts:["{}","[]","()","<>"],ans:1},
{id:11,topic:"PY",level:"easy",q:"How to create a tuple?",opts:["[]","{}","()","<>"],ans:2},
{id:12,topic:"PY",level:"easy",q:"How to create a dict?",opts:["[]","{}","()","<>"],ans:1},
{id:13,topic:"PY",level:"easy",q:"How to create a set?",opts:["[]","{}","()","set()"],ans:3},
{id:14,topic:"PY",level:"easy",q:"len() returns?",opts:["Length/size","First element","Memory","Type"],ans:0},
{id:15,topic:"PY",level:"easy",q:"type() returns?",opts:["Value","Memory","Type","Class name only"],ans:2},
{id:16,topic:"PY",level:"easy",q:"int('5') returns?",opts:["'5'","5","5.0","Error"],ans:1},
{id:17,topic:"PY",level:"easy",q:"str(5) returns?",opts:["5","'5'","5.0","Error"],ans:1},
{id:18,topic:"PY",level:"easy",q:"float('3.14') returns?",opts:["3","3.14","'3.14'","Error"],ans:1},
{id:19,topic:"PY",level:"easy",q:"What is 10 // 3?",opts:["3.33","3","4","1"],ans:1},
{id:20,topic:"PY",level:"easy",q:"What is 10 % 3?",opts:["3","1","0","3.33"],ans:1},
{id:21,topic:"PY",level:"easy",q:"What is 2 ** 5?",opts:["10","25","32","16"],ans:2},
{id:22,topic:"PY",level:"easy",q:"Operator for not equal?",opts:["<>","!=","~=","not="],ans:1},
{id:23,topic:"PY",level:"easy",q:"Operator for logical AND?",opts:["&&","and","&","AND"],ans:1},
{id:24,topic:"PY",level:"easy",q:"Operator for logical OR?",opts:["||","or","|","OR"],ans:1},
{id:25,topic:"PY",level:"easy",q:"Operator for logical NOT?",opts:["!","~","not","NOT"],ans:2},
{id:26,topic:"PY",level:"easy",q:"True and False produces?",opts:["True","False","None","Error"],ans:1},
{id:27,topic:"PY",level:"easy",q:"True or False produces?",opts:["True","False","Error","None"],ans:0},
{id:28,topic:"PY",level:"easy",q:"not True is?",opts:["True","False","None","1"],ans:1},
{id:29,topic:"PY",level:"easy",q:"How to start a for loop over list?",opts:["for(i;i<n;i++)","for i in list:","foreach i in list:","loop i list:"],ans:1},
{id:30,topic:"PY",level:"easy",q:"range(5) generates?",opts:["1..5","0..5","0..4","1..4"],ans:2},
{id:31,topic:"PY",level:"easy",q:"range(1,5) generates?",opts:["1,2,3,4,5","1,2,3,4","0,1,2,3,4","2,3,4"],ans:1},
{id:32,topic:"PY",level:"easy",q:"range(0,10,2) generates?",opts:["0,2,4,6,8","0,2,4,6,8,10","0..10","2,4,6,8"],ans:0},
{id:33,topic:"PY",level:"easy",q:"break statement does?",opts:["Skip iteration","Exit loop","Pause","Restart"],ans:1},
{id:34,topic:"PY",level:"easy",q:"continue statement does?",opts:["Exit loop","Skip rest, next iteration","Pause","Restart loop"],ans:1},
{id:35,topic:"PY",level:"easy",q:"pass statement does?",opts:["Skip","Exit","Nothing (placeholder)","Errors"],ans:2},
{id:36,topic:"PY",level:"easy",q:"What is a mutable type?",opts:["tuple","string","list","int"],ans:2},
{id:37,topic:"PY",level:"easy",q:"What is an immutable type?",opts:["list","dict","tuple","set"],ans:2},
{id:38,topic:"PY",level:"easy",q:"How to append to list?",opts:["list.add(x)","list.push(x)","list.append(x)","list.insert(x)"],ans:2},
{id:39,topic:"PY",level:"easy",q:"How to add multiple to list?",opts:["concat()","extend()","add()","push()"],ans:1},
{id:40,topic:"PY",level:"easy",q:"How to remove last element from list?",opts:["pop()","remove()","del[-1]","Both pop() and del list[-1]"],ans:3},
{id:41,topic:"PY",level:"easy",q:"How to remove value 5 from list?",opts:["list.remove(5)","list.del(5)","list.pop(5)","del 5"],ans:0},
{id:42,topic:"PY",level:"easy",q:"How to get dict value by key?",opts:["d.key","d[key]","d->key","d::key"],ans:1},
{id:43,topic:"PY",level:"easy",q:"How to safely get dict value (no error)?",opts:["d[key]","d.get(key)","d->key","try d[key]"],ans:1},
{id:44,topic:"PY",level:"easy",q:"How to add key to dict?",opts:["d.add(k,v)","d[k] = v","d.append(k,v)","d.insert"],ans:1},
{id:45,topic:"PY",level:"easy",q:"How to delete dict key?",opts:["del d[k]","d.delete(k)","d.remove(k)","del k"],ans:0},
// -------- MEDIUM --------
{id:46,topic:"PY",level:"medium",q:"Output: print(type([1,2,3]))?",opts:["<class 'array'>","<class 'list'>","<class 'tuple'>","<class 'set'>"],ans:1},
{id:47,topic:"PY",level:"medium",q:"Output: print(type({1,2,3}))?",opts:["<class 'list'>","<class 'set'>","<class 'dict'>","<class 'tuple'>"],ans:1},
{id:48,topic:"PY",level:"medium",q:"Output: print(type({1:'a'}))?",opts:["<class 'set'>","<class 'dict'>","<class 'list'>","<class 'tuple'>"],ans:1},
{id:49,topic:"PY",level:"medium",q:"Output: print(type((1,2,3)))?",opts:["<class 'list'>","<class 'tuple'>","<class 'set'>","<class 'dict'>"],ans:1},
{id:50,topic:"PY",level:"medium",q:"Output: print([1,2,3]+[4,5])?",opts:["[5,7,8]","[1,2,3,4,5]","Error","[1,2,3]+[4,5]"],ans:1},
{id:51,topic:"PY",level:"medium",q:"Output: print([1,2]*3)?",opts:["[3,6]","[1,2,1,2,1,2]","Error","6"],ans:1},
{id:52,topic:"PY",level:"medium",q:"Output: print('ab'*3)?",opts:["'ab3'","'ababab'","Error","'ab,ab,ab'"],ans:1},
{id:53,topic:"PY",level:"medium",q:"Output: print('hello'[1])?",opts:["'h'","'e'","'l'","Error"],ans:1},
{id:54,topic:"PY",level:"medium",q:"Output: print('hello'[-1])?",opts:["'h'","'o'","'l'","Error"],ans:1},
{id:55,topic:"PY",level:"medium",q:"Output: print('hello'[1:4])?",opts:["'hell'","'ell'","'hel'","'ello'"],ans:1},
{id:56,topic:"PY",level:"medium",q:"Output: print(len([1,[2,3]]))?",opts:["1","2","3","4"],ans:1},
{id:57,topic:"PY",level:"medium",q:"How to reverse a list?",opts:["l.reverse()","l[::-1]","reversed(l)","All of these"],ans:3},
{id:58,topic:"PY",level:"medium",q:"How to sort a list in-place?",opts:["sort(l)","l.sort()","sorted(l)","arrange(l)"],ans:1},
{id:59,topic:"PY",level:"medium",q:"Difference sort() vs sorted()?",opts:["No diff","sort() in-place; sorted() returns new","sort() faster","sorted() in-place"],ans:1},
{id:60,topic:"PY",level:"medium",q:"How to define keyword arg?",opts:["f(a:1)","f(a=1)","f(a->1)","f($a=1)"],ans:1},
{id:61,topic:"PY",level:"medium",q:"What does *args mean?",opts:["Single arg","Variable-length positional args","Pointer","Keyword args"],ans:1},
{id:62,topic:"PY",level:"medium",q:"What does **kwargs mean?",opts:["Power","Variable-length keyword args","Pointer to pointer","List args"],ans:1},
{id:63,topic:"PY",level:"medium",q:"Lambda expression syntax?",opts:["lambda x: x*2","lambda(x){x*2}","fn x=>x*2","\\x.x*2"],ans:0},
{id:64,topic:"PY",level:"medium",q:"map(f, list) returns?",opts:["New list","map object (iterator)","Tuple","String"],ans:1},
{id:65,topic:"PY",level:"medium",q:"filter(f, list) returns?",opts:["List","filter object","Boolean","Tuple"],ans:1},
{id:66,topic:"PY",level:"medium",q:"How to convert map/filter to list?",opts:["list(m)","tuple(m)","str(m)","array(m)"],ans:0},
{id:67,topic:"PY",level:"medium",q:"List comprehension: [x*2 for x in range(3)]?",opts:["[0,1,2]","[0,2,4]","[2,4,6]","Error"],ans:1},
{id:68,topic:"PY",level:"medium",q:"Dict comprehension: {x: x*2 for x in range(3)}?",opts:["{0:0, 1:2, 2:4}","[0,2,4]","{0,2,4}","Error"],ans:0},
{id:69,topic:"PY",level:"medium",q:"Open file in read mode?",opts:["'r'","'w'","'a'","'x'"],ans:0},
{id:70,topic:"PY",level:"medium",q:"Open file in write mode (overwrites)?",opts:["'r'","'w'","'a'","'x'"],ans:1},
{id:71,topic:"PY",level:"medium",q:"Open file in append mode?",opts:["'r'","'w'","'a'","'x'"],ans:2},
{id:72,topic:"PY",level:"medium",q:"What does 'with open(f) as ...' do?",opts:["Locks file","Auto-closes file after block","Hides","Backups"],ans:1},
{id:73,topic:"PY",level:"medium",q:"f.readlines() returns?",opts:["Single string","List of lines","Generator","Error"],ans:1},
{id:74,topic:"PY",level:"medium",q:"Which block catches exceptions?",opts:["try-catch","try-except","catch-throw","handle"],ans:1},
{id:75,topic:"PY",level:"medium",q:"Which block runs always?",opts:["except","finally","else","always"],ans:1},
{id:76,topic:"PY",level:"medium",q:"Which block runs if no exception?",opts:["finally","except","else","done"],ans:2},
{id:77,topic:"PY",level:"medium",q:"How to raise custom exception?",opts:["throw","raise","error","emit"],ans:1},
{id:78,topic:"PY",level:"medium",q:"Common exception for missing key in dict?",opts:["IndexError","KeyError","ValueError","AttributeError"],ans:1},
{id:79,topic:"PY",level:"medium",q:"Exception for invalid index in list?",opts:["IndexError","KeyError","TypeError","NameError"],ans:0},
{id:80,topic:"PY",level:"medium",q:"Exception for divide by 0?",opts:["MathError","DivisionError","ZeroDivisionError","ArithmeticError"],ans:2},
{id:81,topic:"PY",level:"medium",q:"How to import only one func?",opts:["import math.sqrt","from math import sqrt","using math.sqrt","import sqrt from math"],ans:1},
{id:82,topic:"PY",level:"medium",q:"How to alias an import?",opts:["import math as m","import math = m","alias m = math","import m from math"],ans:0},
{id:83,topic:"PY",level:"medium",q:"What does 'self' refer to inside a class method?",opts:["Class","Instance","Module","Parent"],ans:1},
{id:84,topic:"PY",level:"medium",q:"What is __init__?",opts:["Destructor","Constructor","Static method","Class method"],ans:1},
{id:85,topic:"PY",level:"medium",q:"How to inherit from a class?",opts:["class B(A):","class B extends A:","class B :: A","class B from A:"],ans:0},
{id:86,topic:"PY",level:"medium",q:"How to call parent constructor?",opts:["parent()","super().__init__()","this()","base()"],ans:1},
{id:87,topic:"PY",level:"medium",q:"What does __str__ method define?",opts:["Comparison","String representation","Constructor","Length"],ans:1},
{id:88,topic:"PY",level:"medium",q:"Private attribute convention?",opts:["__name","#name","_name","private name"],ans:0},
{id:89,topic:"PY",level:"medium",q:"Output: print(list(range(3)))?",opts:["[1,2,3]","[0,1,2]","[0,1,2,3]","Error"],ans:1},
{id:90,topic:"PY",level:"medium",q:"Output: print('abc'.upper())?",opts:["'abc'","'ABC'","'Abc'","Error"],ans:1},
{id:91,topic:"PY",level:"medium",q:"Output: print('Hi'.lower())?",opts:["'HI'","'hi'","'Hi'","Error"],ans:1},
{id:92,topic:"PY",level:"medium",q:"Output: print('a,b,c'.split(','))?",opts:["'abc'","['a','b','c']","['a,b,c']","Error"],ans:1},
{id:93,topic:"PY",level:"medium",q:"Output: print('-'.join(['a','b','c']))?",opts:["'abc'","'a-b-c'","'a,b,c'","Error"],ans:1},
{id:94,topic:"PY",level:"medium",q:"Output: print('  hi  '.strip())?",opts:["'  hi  '","'hi'","'hi  '","'  hi'"],ans:1},
{id:95,topic:"PY",level:"medium",q:"Output: print('abc'.find('b'))?",opts:["0","1","-1","2"],ans:1},
{id:96,topic:"PY",level:"medium",q:"Output: print('abc'.replace('a','x'))?",opts:["'abc'","'xbc'","'abx'","'xyz'"],ans:1},
{id:97,topic:"PY",level:"medium",q:"Output: print(sorted([3,1,2]))?",opts:["[3,1,2]","[1,2,3]","[3,2,1]","Error"],ans:1},
{id:98,topic:"PY",level:"medium",q:"Output: print(sum([1,2,3]))?",opts:["6","123","1.5","Error"],ans:0},
{id:99,topic:"PY",level:"medium",q:"Output: print(max([4,2,8,3]))?",opts:["2","4","8","3"],ans:2},
{id:100,topic:"PY",level:"medium",q:"Output: print(min([4,2,8,3]))?",opts:["8","2","3","4"],ans:1},
{id:101,topic:"PY",level:"medium",q:"Output: print(abs(-5))?",opts:["-5","5","0","Error"],ans:1},
{id:102,topic:"PY",level:"medium",q:"Output: print(round(3.7))?",opts:["3","4","3.7","Error"],ans:1},
{id:103,topic:"PY",level:"medium",q:"Output: print(round(3.456, 1))?",opts:["3","3.5","3.46","3.4"],ans:1},
{id:104,topic:"PY",level:"medium",q:"Output of: x=5\\ny=10\\nprint(x,y)?",opts:["5 10","5,10","'5 10'","Error"],ans:0},
{id:105,topic:"PY",level:"medium",q:"What does f'{x}' do?",opts:["String literal","f-string interpolation","Format","Print"],ans:1},
// -------- HARD --------
{id:106,topic:"PY",level:"hard",q:"Output: print([1,2,3]==[1,2,3])?",opts:["True","False","Error","None"],ans:0},
{id:107,topic:"PY",level:"hard",q:"Output: print([1,2,3] is [1,2,3])?",opts:["True","False","Error","None"],ans:1},
{id:108,topic:"PY",level:"hard",q:"Difference '==' vs 'is'?",opts:["No diff","== checks value, is checks identity","is checks value","== checks type"],ans:1},
{id:109,topic:"PY",level:"hard",q:"What does enumerate(['a','b']) yield?",opts:["[a,b]","(0,'a'),(1,'b')","[0,1]","Error"],ans:1},
{id:110,topic:"PY",level:"hard",q:"What does zip([1,2],[3,4]) produce?",opts:["[1,2,3,4]","[(1,3),(2,4)]","[[1,3],[2,4]]","Error"],ans:1},
{id:111,topic:"PY",level:"hard",q:"What is a decorator?",opts:["Class","Function wrapping another function","Variable","Module"],ans:1},
{id:112,topic:"PY",level:"hard",q:"How is a decorator applied?",opts:["@decorator","#decorator","$decorator","!decorator"],ans:0},
{id:113,topic:"PY",level:"hard",q:"What does yield do?",opts:["Return","Pauses generator and returns value","Error","Loop"],ans:1},
{id:114,topic:"PY",level:"hard",q:"What does next() do on a generator?",opts:["Restarts","Returns next yielded value","Skips","Stops"],ans:1},
{id:115,topic:"PY",level:"hard",q:"What is GIL in Python?",opts:["Global Interpreter Lock","Generic Iterator Loop","Garbage Collector","None"],ans:0},
{id:116,topic:"PY",level:"hard",q:"Output: print({1,2,2,3})?",opts:["{1,2,2,3}","{1,2,3}","[1,2,3]","Error"],ans:1},
{id:117,topic:"PY",level:"hard",q:"Output: print({'a':1,'b':2}.keys())?",opts:["['a','b']","dict_keys(['a','b'])","('a','b')","{'a','b'}"],ans:1},
{id:118,topic:"PY",level:"hard",q:"Output: print(1==True)?",opts:["True","False","1","Error"],ans:0},
{id:119,topic:"PY",level:"hard",q:"Output: print(0==False)?",opts:["True","False","0","Error"],ans:0},
{id:120,topic:"PY",level:"hard",q:"Output: print('5'+'3')?",opts:["8","'53'","53","Error"],ans:1},
{id:121,topic:"PY",level:"hard",q:"Output: print('5'*3)?",opts:["15","'555'","'5*3'","Error"],ans:1},
{id:122,topic:"PY",level:"hard",q:"Output: print(list('abc'))?",opts:["['abc']","['a','b','c']","'abc'","Error"],ans:1},
{id:123,topic:"PY",level:"hard",q:"What is inheritance in OOP?",opts:["Copy class","Child class gets parent's attributes/methods","Composition","Polymorphism"],ans:1},
{id:124,topic:"PY",level:"hard",q:"What is polymorphism?",opts:["Many forms — same method behaves diff in subclasses","Many classes","Many objects","Many vars"],ans:0},
{id:125,topic:"PY",level:"hard",q:"What is encapsulation?",opts:["Hide internal details, expose interface","Inherit","Copy","Loop"],ans:0},
{id:126,topic:"PY",level:"hard",q:"What is abstraction?",opts:["Hide complexity, show essentials","Loops","File I/O","Threads"],ans:0},
{id:127,topic:"PY",level:"hard",q:"Decorator @staticmethod means?",opts:["Bound to instance","Bound to class without self","Bound to module","Random"],ans:1},
{id:128,topic:"PY",level:"hard",q:"Decorator @classmethod first arg is?",opts:["self","cls","obj","this"],ans:1},
{id:129,topic:"PY",level:"hard",q:"How to load JSON file in Python?",opts:["json.load(f)","f.json()","load_json(f)","read_json(f)"],ans:0},
{id:130,topic:"PY",level:"hard",q:"How to dump Python obj to JSON file?",opts:["json.dump(obj,f)","json.save(obj,f)","obj.toJson()","write_json(obj,f)"],ans:0},
{id:131,topic:"PY",level:"hard",q:"json.dumps() returns?",opts:["File","JSON string","List","Error"],ans:1},
{id:132,topic:"PY",level:"hard",q:"What does 'global x' do inside function?",opts:["Local","Declares x refers to global var","Hides","Errors"],ans:1},
{id:133,topic:"PY",level:"hard",q:"What does 'nonlocal x' do?",opts:["Global","Refers to enclosing scope var","Local","Errors"],ans:1},
{id:134,topic:"PY",level:"hard",q:"Output: print(bool([]))?",opts:["True","False","None","Error"],ans:1},
{id:135,topic:"PY",level:"hard",q:"Output: print(bool([0]))?",opts:["False","True","None","Error"],ans:1},
{id:136,topic:"PY",level:"hard",q:"Output: print(bool(''))?",opts:["True","False","None","Error"],ans:1},
{id:137,topic:"PY",level:"hard",q:"Output: print(bool('0'))?",opts:["True","False","None","Error"],ans:0},
{id:138,topic:"PY",level:"hard",q:"What does any([0,1,0]) return?",opts:["True","False","1","2"],ans:0},
{id:139,topic:"PY",level:"hard",q:"What does all([1,1,0]) return?",opts:["True","False","1","2"],ans:1},
{id:140,topic:"PY",level:"hard",q:"What is a stack (LIFO)?",opts:["First-In-First-Out","Last-In-First-Out","Sorted","Random"],ans:1},
{id:141,topic:"PY",level:"hard",q:"What is a queue (FIFO)?",opts:["Last-In-First-Out","First-In-First-Out","Sorted","Random"],ans:1},
{id:142,topic:"PY",level:"hard",q:"In Python, what list method pops first item (queue-like)?",opts:["pop()","pop(0)","pop(-1)","first()"],ans:1},
{id:143,topic:"PY",level:"hard",q:"What does collections.deque support efficiently?",opts:["Random index","appendleft / popleft (O(1))","Sorting","Hashing"],ans:1},
{id:144,topic:"PY",level:"hard",q:"What is recursion?",opts:["Loop","Function calling itself","Inheritance","Exception"],ans:1},
{id:145,topic:"PY",level:"hard",q:"What's the base case of recursion?",opts:["Loop start","Condition stopping recursion","Else block","First call"],ans:1},
{id:146,topic:"PY",level:"hard",q:"Output: print(2**10)?",opts:["100","1024","20","Error"],ans:1},
{id:147,topic:"PY",level:"hard",q:"Output: print(10**0)?",opts:["0","1","10","Error"],ans:1},
{id:148,topic:"PY",level:"hard",q:"Output: print(divmod(10,3))?",opts:["(3,1)","[3,1]","(1,3)","3.33"],ans:0},
{id:149,topic:"PY",level:"hard",q:"Output: print(pow(2,3))?",opts:["6","8","9","Error"],ans:1},
{id:150,topic:"PY",level:"hard",q:"Output: print(pow(2,3,5))?",opts:["6","3 (2^3 mod 5)","8","Error"],ans:1}
]

};
