/* ============================================================
   QUESTION POOL — extras  (appends to POOL.HTML/CSS/JS/PY)
   ------------------------------------------------------------
   Loaded AFTER question_pool.js — merges into the global POOL.
   ============================================================ */

(function () {

// ============================================================
// HTML — extras  (target ~120 new → topic total ~200)
// ============================================================
const HTML_EXTRA = [
// EASY
{id:101,topic:"HTML",level:"easy",q:"Which tag defines a thematic section?",opts:["<div>","<section>","<part>","<group>"],ans:1},
{id:102,topic:"HTML",level:"easy",q:"Which tag for an aside / sidebar?",opts:["<side>","<aside>","<bar>","<extra>"],ans:1},
{id:103,topic:"HTML",level:"easy",q:"Which tag is for embedded SVG?",opts:["<svg>","<vector>","<graphic>","<picture>"],ans:0},
{id:104,topic:"HTML",level:"easy",q:"Which attribute makes input read-only?",opts:["readonly","disabled","locked","static"],ans:0},
{id:105,topic:"HTML",level:"easy",q:"Which type of input shows a slider?",opts:["range","slider","number","scale"],ans:0},
{id:106,topic:"HTML",level:"easy",q:"Which type creates a file upload field?",opts:["upload","file","attach","data"],ans:1},
{id:107,topic:"HTML",level:"easy",q:"<textarea> is used for?",opts:["Single-line text","Multi-line text input","Plain text display","Read-only text"],ans:1},
{id:108,topic:"HTML",level:"easy",q:"Which tag groups <option>s into a category?",opts:["<group>","<category>","<optgroup>","<options>"],ans:2},
{id:109,topic:"HTML",level:"easy",q:"Which tag for marked/highlighted text?",opts:["<highlight>","<mark>","<yellow>","<hl>"],ans:1},
{id:110,topic:"HTML",level:"easy",q:"Which tag for deleted/strikethrough text?",opts:["<strike>","<del>","<remove>","<line>"],ans:1},
{id:111,topic:"HTML",level:"easy",q:"Which tag for inserted text (underlined)?",opts:["<ins>","<add>","<insert>","<u>"],ans:0},
{id:112,topic:"HTML",level:"easy",q:"Which tag for subscript text?",opts:["<sub>","<lower>","<down>","<inf>"],ans:0},
{id:113,topic:"HTML",level:"easy",q:"Which tag for superscript text?",opts:["<sup>","<upper>","<top>","<exp>"],ans:0},
{id:114,topic:"HTML",level:"easy",q:"Default value of form's action attribute?",opts:["GET","Current URL (self-submit)","blank","Server"],ans:1},
{id:115,topic:"HTML",level:"easy",q:"Which attribute hides element from view?",opts:["invisible","hidden","display='none'","show='false'"],ans:1},
{id:116,topic:"HTML",level:"easy",q:"Which attribute sets tab order?",opts:["taborder","tabindex","tab","order"],ans:1},
{id:117,topic:"HTML",level:"easy",q:"Which attribute lets users drag an element?",opts:["draggable","drag","movable","draggable='true'"],ans:0},
{id:118,topic:"HTML",level:"easy",q:"What does <wbr> tag indicate?",opts:["Word break opportunity","Bold word","Word wrap","Width break"],ans:0},
{id:119,topic:"HTML",level:"easy",q:"Which tag groups options in <select>?",opts:["<group>","<optgroup>","<options>","<list>"],ans:1},
{id:120,topic:"HTML",level:"easy",q:"Which attribute on form sets file encoding?",opts:["encoding","enctype","format","type"],ans:1},
// MEDIUM
{id:121,topic:"HTML",level:"medium",q:"Default enctype of <form>?",opts:["application/x-www-form-urlencoded","multipart/form-data","text/plain","application/json"],ans:0},
{id:122,topic:"HTML",level:"medium",q:"Which enctype is needed for file uploads?",opts:["application/x-www-form-urlencoded","multipart/form-data","text/plain","files/encoded"],ans:1},
{id:123,topic:"HTML",level:"medium",q:"Which tag represents a key/keyboard input?",opts:["<key>","<kbd>","<keyb>","<press>"],ans:1},
{id:124,topic:"HTML",level:"medium",q:"Which tag represents sample (program) output?",opts:["<output>","<samp>","<code>","<pre>"],ans:1},
{id:125,topic:"HTML",level:"medium",q:"Which tag represents a variable?",opts:["<var>","<v>","<variable>","<def>"],ans:0},
{id:126,topic:"HTML",level:"medium",q:"Which tag creates a citation?",opts:["<quote>","<cite>","<ref>","<source>"],ans:1},
{id:127,topic:"HTML",level:"medium",q:"Which tag represents an abbreviation with tooltip?",opts:["<abbr>","<acronym>","<short>","<def>"],ans:0},
{id:128,topic:"HTML",level:"medium",q:"<address> tag is used for?",opts:["Any address","Contact info, owner of document/article","Mailing address","Email"],ans:1},
{id:129,topic:"HTML",level:"medium",q:"<time> tag is for?",opts:["Clock display","Machine-readable date/time","Animation timing","Just text"],ans:1},
{id:130,topic:"HTML",level:"medium",q:"<figure> + <figcaption> are for?",opts:["Forms","Self-contained content with caption (images, etc.)","Tables","Inline images"],ans:1},
{id:131,topic:"HTML",level:"medium",q:"<audio controls> shows?",opts:["Nothing","Default playback controls","Volume only","Play button only"],ans:1},
{id:132,topic:"HTML",level:"medium",q:"<video poster='x.jpg'> means?",opts:["Title image","Preview image before play","Bookmark","Subtitle"],ans:1},
{id:133,topic:"HTML",level:"medium",q:"Which input type allows multiple values?",opts:["text with multiple","file with multiple","email with multiple","Both b and c"],ans:3},
{id:134,topic:"HTML",level:"medium",q:"Which attribute auto-focuses an input?",opts:["focus","autofocus","autoFocus","focused"],ans:1},
{id:135,topic:"HTML",level:"medium",q:"Which attribute provides input hint?",opts:["hint","placeholder","ghost","preview"],ans:1},
{id:136,topic:"HTML",level:"medium",q:"Which attribute restricts input character count?",opts:["limit","maxlength","max-chars","length"],ans:1},
{id:137,topic:"HTML",level:"medium",q:"Which attribute provides pattern validation?",opts:["regex","validate","pattern","format"],ans:2},
{id:138,topic:"HTML",level:"medium",q:"<datalist> works with?",opts:["<select>","<input list='id'>","<table>","<form>"],ans:1},
{id:139,topic:"HTML",level:"medium",q:"What's the use of <slot>?",opts:["Animation","Web Components content insertion","Variable","Form input"],ans:1},
{id:140,topic:"HTML",level:"medium",q:"What's the difference: <b> vs <strong>?",opts:["Same","<b> visual, <strong> semantic importance","<strong> visual only","<b> deprecated"],ans:1},
{id:141,topic:"HTML",level:"medium",q:"What's the difference: <i> vs <em>?",opts:["Same","<i> visual italic, <em> semantic emphasis","<em> visual only","<i> deprecated"],ans:1},
{id:142,topic:"HTML",level:"medium",q:"<canvas> is used for?",opts:["Form","Drawing graphics via JS","Layout","Audio"],ans:1},
{id:143,topic:"HTML",level:"medium",q:"<map> + <area> are for?",opts:["Geography","Image map (clickable regions)","Layout","Routing"],ans:1},
{id:144,topic:"HTML",level:"medium",q:"Which meta tag controls page caching?",opts:["<meta cache>",'<meta http-equiv="Cache-Control" content="...">',"<cache>","<noindex>"],ans:1},
{id:145,topic:"HTML",level:"medium",q:"Which meta sets the page description?",opts:['<meta name="description" content="...">','<desc>','<meta content="desc">','<info>'],ans:0},
{id:146,topic:"HTML",level:"medium",q:"Which meta refreshes the page?",opts:['<meta refresh>','<meta http-equiv="refresh" content="5">','<auto-refresh>','<reload>'],ans:1},
{id:147,topic:"HTML",level:"medium",q:"Open Graph tags are prefixed with?",opts:["og:","fb:","graph:","meta:"],ans:0},
{id:148,topic:"HTML",level:"medium",q:"<base href> sets?",opts:["Default base URL for relative links","Page title","Favicon","Stylesheet"],ans:0},
{id:149,topic:"HTML",level:"medium",q:"Which event attribute fires on form submit?",opts:["onsend","onsubmit","onclick","onform"],ans:1},
{id:150,topic:"HTML",level:"medium",q:"Which event fires when input value changes (after blur)?",opts:["onchange","oninput","onclick","onkeyup"],ans:0},
// HARD
{id:151,topic:"HTML",level:"hard",q:"oninput vs onchange — difference?",opts:["Same","oninput on every keystroke; onchange when committed","Reversed","oninput async"],ans:1},
{id:152,topic:"HTML",level:"hard",q:"What does formnovalidate on a submit button do?",opts:["Disables button","Skips form validation for that submit","Reloads form","Logs"],ans:1},
{id:153,topic:"HTML",level:"hard",q:"What does accept='image/*' on <input type='file'> do?",opts:["Filters file picker to images","Validates server-side","Resizes","No effect"],ans:0},
{id:154,topic:"HTML",level:"hard",q:"What's the result of crossorigin attribute on <script>?",opts:["No effect","Enables CORS for the script","Caches","Disables script"],ans:1},
{id:155,topic:"HTML",level:"hard",q:"What's <link rel='preload'> for?",opts:["Late loading","Force browser to fetch resource early","Skip","Cache only"],ans:1},
{id:156,topic:"HTML",level:"hard",q:"<link rel='prefetch'> vs preload?",opts:["Same","prefetch = future nav hint, preload = immediate","Reversed","No diff"],ans:1},
{id:157,topic:"HTML",level:"hard",q:"What is shadow DOM?",opts:["Hidden DOM","Encapsulated DOM tree of a Web Component","CSS","Animation"],ans:1},
{id:158,topic:"HTML",level:"hard",q:"Which element has open/closed shadow DOM?",opts:["<div>","<template>","Custom Elements via attachShadow()","<iframe>"],ans:2},
{id:159,topic:"HTML",level:"hard",q:"What does srcset on <img> do?",opts:["Multiple srcs","Lists alternate images for different DPRs/widths","Lazy load","Backup"],ans:1},
{id:160,topic:"HTML",level:"hard",q:"What does loading='lazy' on <img> do?",opts:["Spinner","Delays loading until near viewport","Disables","Cache"],ans:1},
{id:161,topic:"HTML",level:"hard",q:"What does decoding='async' on <img> do?",opts:["Loads async","Allows async image decoding","No effect","Compresses"],ans:1},
{id:162,topic:"HTML",level:"hard",q:"role attribute provides?",opts:["JS role","Accessibility role for screen readers","CSS role","Display"],ans:1},
{id:163,topic:"HTML",level:"hard",q:"aria-label is used to?",opts:["Set CSS","Give accessible name when text isn't visible","Hide","Disable"],ans:1},
{id:164,topic:"HTML",level:"hard",q:"What is microdata?",opts:["Small data","Structured data in HTML via itemscope/itemtype","Cookies","LocalStorage"],ans:1},
{id:165,topic:"HTML",level:"hard",q:"What is the picture element used for?",opts:["Multiple <img>","Art direction / format selection","Animation","Video"],ans:1},
{id:166,topic:"HTML",level:"hard",q:"What's the difference: <div> vs <section>?",opts:["Same","<div> generic, <section> semantic (with heading)","<section> deprecated","<div> hidden"],ans:1},
{id:167,topic:"HTML",level:"hard",q:"Result of <button type='button'> inside form?",opts:["Submits","Does NOT submit (just a button)","Resets","Cancels"],ans:1},
{id:168,topic:"HTML",level:"hard",q:"Default type of <button> inside form?",opts:["button","submit","reset","none"],ans:1},
{id:169,topic:"HTML",level:"hard",q:"Which attribute makes a checkbox required?",opts:["mandatory","required","needed","check"],ans:1},
{id:170,topic:"HTML",level:"hard",q:"What's CSP meta tag?",opts:["Content Security Policy: restricts allowed sources","Cookie","Cache","Charset"],ans:0},
{id:171,topic:"HTML",level:"hard",q:"What does inputmode attribute control?",opts:["Type","Mobile virtual keyboard layout","Visibility","Encoding"],ans:1},
{id:172,topic:"HTML",level:"hard",q:"What's the difference between block & inline-block?",opts:["Same","inline-block flows inline but respects width/height","Reversed","No diff"],ans:1},
{id:173,topic:"HTML",level:"hard",q:"What's the default value of contenteditable?",opts:["true","false","inherit","null"],ans:1},
{id:174,topic:"HTML",level:"hard",q:"What does the spellcheck attribute do?",opts:["Validates","Enables/disables browser spell check","Auto-corrects","No effect"],ans:1},
{id:175,topic:"HTML",level:"hard",q:"What's <track> element used for?",opts:["GPS","Captions/subtitles for media","Animation","Counter"],ans:1},
{id:176,topic:"HTML",level:"hard",q:"What does <source> tag do inside <picture>/<video>?",opts:["Loads JS","Provides alternate sources/formats","Embeds","Links"],ans:1},
{id:177,topic:"HTML",level:"hard",q:"What's the inert attribute?",opts:["Disables","Makes element non-interactive AND not in tab order","Hides","Read-only"],ans:1},
{id:178,topic:"HTML",level:"hard",q:"What's the popover attribute (newer HTML)?",opts:["Tooltip","Declares an element as popover, controlled by popovertarget","CSS only","Tooltip text"],ans:1},
{id:179,topic:"HTML",level:"hard",q:"What's the dir attribute?",opts:["Directory","Text direction (ltr/rtl/auto)","Display","Drag"],ans:1},
{id:180,topic:"HTML",level:"hard",q:"What does the lang attribute do?",opts:["Sets variable","Specifies the language of element/document","Encoding","Locale formatting"],ans:1}
];

// ============================================================
// CSS — extras  (target ~120 new → topic total ~200)
// ============================================================
const CSS_EXTRA = [
// EASY
{id:101,topic:"CSS",level:"easy",q:"How to make element full width?",opts:["width:full","width:100%","width:max","width:total"],ans:1},
{id:102,topic:"CSS",level:"easy",q:"Property to underline text?",opts:["underline","text-decoration:underline","line:under","text-line"],ans:1},
{id:103,topic:"CSS",level:"easy",q:"How to set image as background?",opts:["bg:url(...)","background-image:url(...)","background:image(...)","img:url(...)"],ans:1},
{id:104,topic:"CSS",level:"easy",q:"Property to repeat background?",opts:["bg-repeat","background-repeat","tile","fill"],ans:1},
{id:105,topic:"CSS",level:"easy",q:"Property to position background?",opts:["bg-pos","background-position","bg-place","place-bg"],ans:1},
{id:106,topic:"CSS",level:"easy",q:"Property to size background image?",opts:["bg-size","background-size","img-size","size"],ans:1},
{id:107,topic:"CSS",level:"easy",q:"How to make image cover entire box?",opts:["background-size:full","background-size:cover","cover:true","fit:full"],ans:1},
{id:108,topic:"CSS",level:"easy",q:"How to make image fit inside box (no crop)?",opts:["background-size:fit","background-size:contain","contain:true","fit:in"],ans:1},
{id:109,topic:"CSS",level:"easy",q:"Property to make text italic?",opts:["italic:true","font-style:italic","style:italic","text:italic"],ans:1},
{id:110,topic:"CSS",level:"easy",q:"Property to remove default list bullets?",opts:["bullet:none","list-style:none","style:none","no-bullets"],ans:1},
{id:111,topic:"CSS",level:"easy",q:"How to make element disappear (hide visually)?",opts:["hide:true","display:none","visibility:none","invisible:true"],ans:1},
{id:112,topic:"CSS",level:"easy",q:"How to add border?",opts:["border:1px solid red","border-line:red","outline:1px","stroke:red"],ans:0},
{id:113,topic:"CSS",level:"easy",q:"Which property changes mouse on hover to hand?",opts:["mouse:hand","cursor:pointer","cursor:hand","point:true"],ans:1},
{id:114,topic:"CSS",level:"easy",q:"Property to wrap long text?",opts:["wrap:true","word-wrap:break-word","text-wrap:wrap","wrap-text"],ans:1},
{id:115,topic:"CSS",level:"easy",q:"How to set font family?",opts:["font:Arial","font-family:Arial","family:Arial","style:Arial"],ans:1},
{id:116,topic:"CSS",level:"easy",q:"Default font size in most browsers?",opts:["12px","14px","16px","18px"],ans:2},
{id:117,topic:"CSS",level:"easy",q:"Property to set opacity?",opts:["alpha","opacity","transparency","fade"],ans:1},
{id:118,topic:"CSS",level:"easy",q:"opacity: 0 means?",opts:["Fully visible","Fully invisible","Half visible","Grey"],ans:1},
{id:119,topic:"CSS",level:"easy",q:"opacity: 1 means?",opts:["Fully invisible","Half visible","Fully visible","No effect"],ans:2},
{id:120,topic:"CSS",level:"easy",q:"Property for line spacing?",opts:["spacing","line-height","row-gap","leading"],ans:1},
// MEDIUM
{id:121,topic:"CSS",level:"medium",q:"What is the box model order (outside to inside)?",opts:["content/padding/border/margin","margin/border/padding/content","border/margin/padding/content","margin/padding/border/content"],ans:1},
{id:122,topic:"CSS",level:"medium",q:"With box-sizing:content-box, width includes?",opts:["Everything","Just content","Content + padding","Content + border"],ans:1},
{id:123,topic:"CSS",level:"medium",q:"max-width:100% is useful for?",opts:["Centering","Responsive images / boxes never overflow","Hide","Fixed size"],ans:1},
{id:124,topic:"CSS",level:"medium",q:"min-width prevents element from being?",opts:["Wider","Narrower than that value","Tall","Hidden"],ans:1},
{id:125,topic:"CSS",level:"medium",q:"What does white-space:pre do?",opts:["Hide","Preserve whitespace and newlines (like <pre>)","Wrap","Trim"],ans:1},
{id:126,topic:"CSS",level:"medium",q:"What does text-overflow:ellipsis do?",opts:["Show '...' for clipped overflowing text","Hide","Wrap","Stretch"],ans:0},
{id:127,topic:"CSS",level:"medium",q:"What's needed for text-overflow:ellipsis to work?",opts:["Nothing extra","overflow:hidden + white-space:nowrap","display:flex","position:fixed"],ans:1},
{id:128,topic:"CSS",level:"medium",q:"What does float:left do?",opts:["Floats element to left","Centers","Hides","Stretches"],ans:0},
{id:129,topic:"CSS",level:"medium",q:"What does clear:both do?",opts:["Remove all CSS","Move below both left/right floats","Center","Hide"],ans:1},
{id:130,topic:"CSS",level:"medium",q:"In flexbox, default align-items is?",opts:["center","stretch","flex-start","flex-end"],ans:1},
{id:131,topic:"CSS",level:"medium",q:"In flexbox, default justify-content is?",opts:["center","flex-start","space-between","stretch"],ans:1},
{id:132,topic:"CSS",level:"medium",q:"flex-grow controls?",opts:["Initial size","How much item grows relative to siblings","Shrink","Order"],ans:1},
{id:133,topic:"CSS",level:"medium",q:"flex-shrink controls?",opts:["How much item shrinks if needed","Grow","Order","Size"],ans:0},
{id:134,topic:"CSS",level:"medium",q:"flex-basis sets?",opts:["Final size","Initial main-axis size before grow/shrink","Order","Wrap"],ans:1},
{id:135,topic:"CSS",level:"medium",q:"flex-direction:column makes main axis?",opts:["Horizontal","Vertical","Diagonal","Reversed"],ans:1},
{id:136,topic:"CSS",level:"medium",q:"In grid, fr unit means?",opts:["Frame","Fraction of available space","Fixed","Free"],ans:1},
{id:137,topic:"CSS",level:"medium",q:"grid-template-areas defines?",opts:["Visual layout via named areas","Variables","Mixins","Animations"],ans:0},
{id:138,topic:"CSS",level:"medium",q:"gap property used for?",opts:["Padding","Spacing between flex/grid items","Border","Margin"],ans:1},
{id:139,topic:"CSS",level:"medium",q:"What's repeat(3, 1fr) in grid?",opts:["3 cols of 1fr","1 col of 3fr","Errors","Repeats text"],ans:0},
{id:140,topic:"CSS",level:"medium",q:"What's auto-fill vs auto-fit in grid?",opts:["Same","auto-fill keeps empty tracks; auto-fit collapses them","Reversed","No diff"],ans:1},
{id:141,topic:"CSS",level:"medium",q:"position:static element responds to top/left/etc.?",opts:["Yes","No","Only top","Only left"],ans:1},
{id:142,topic:"CSS",level:"medium",q:"How to vertically center with flex?",opts:["justify-content:center","align-items:center","Both (with display:flex)","margin:auto only"],ans:2},
{id:143,topic:"CSS",level:"medium",q:"How to horizontally center a block element?",opts:["text-align:center","margin: 0 auto","center:true","display:center"],ans:1},
{id:144,topic:"CSS",level:"medium",q:"Property for fixed table layout?",opts:["table:fixed","table-layout:fixed","layout-table:fixed","fixed:true"],ans:1},
{id:145,topic:"CSS",level:"medium",q:"How to collapse table borders?",opts:["border-collapse:collapse","border:collapse","collapse:borders","table:collapse"],ans:0},
{id:146,topic:"CSS",level:"medium",q:"How to apply different style on odd rows?",opts:[":odd",":nth-child(odd)",":alternate",":every(2)"],ans:1},
{id:147,topic:"CSS",level:"medium",q:":nth-of-type(2) means?",opts:["Second element","Second of same tag among siblings","Second child","Last 2"],ans:1},
{id:148,topic:"CSS",level:"medium",q:":root selector represents?",opts:["body","html element","window","Root of stylesheet"],ans:1},
{id:149,topic:"CSS",level:"medium",q:":focus pseudo-class fires when?",opts:["Hover","Element has keyboard focus","Disabled","Selected"],ans:1},
{id:150,topic:"CSS",level:"medium",q:":disabled selects?",opts:["Hidden","Disabled form elements","Empty","Read-only"],ans:1},
// HARD
{id:151,topic:"CSS",level:"hard",q:":focus-visible vs :focus?",opts:["Same","focus-visible only when keyboard nav (not mouse)","Reversed","focus-visible deprecated"],ans:1},
{id:152,topic:"CSS",level:"hard",q:":has() selector is?",opts:["Old hack","Parent selector — selects el that has matching descendant","Same as :is","Sibling selector"],ans:1},
{id:153,topic:"CSS",level:"hard",q:":is() and :where() difference?",opts:["No diff","Specificity: :is takes max of args, :where contributes 0","Reversed","Both 0 specificity"],ans:1},
{id:154,topic:"CSS",level:"hard",q:"CSS specificity for inline style?",opts:["0,0,0,1","0,1,0,0","1,0,0,0","Highest (overrides id)"],ans:2},
{id:155,topic:"CSS",level:"hard",q:"!important can be overridden by?",opts:["Nothing","More specific !important higher in cascade","Inline","Specificity"],ans:1},
{id:156,topic:"CSS",level:"hard",q:"Specificity points for class?",opts:["1,0,0","0,1,0","0,0,1","10"],ans:1},
{id:157,topic:"CSS",level:"hard",q:"Specificity points for id?",opts:["1,0,0","0,1,0","0,0,1","100"],ans:0},
{id:158,topic:"CSS",level:"hard",q:"Specificity points for tag/element?",opts:["1,0,0","0,1,0","0,0,1","1"],ans:2},
{id:159,topic:"CSS",level:"hard",q:"What is currentColor?",opts:["Variable","Keyword equal to current text 'color'","Last colour","Theme"],ans:1},
{id:160,topic:"CSS",level:"hard",q:"What does inherit value do?",opts:["Errors","Forces inheritance from parent","Reset","Default"],ans:1},
{id:161,topic:"CSS",level:"hard",q:"What does initial value do?",opts:["No effect","Resets to property's spec default","Inherits","Hide"],ans:1},
{id:162,topic:"CSS",level:"hard",q:"What does unset do?",opts:["Removes property","Inherits if inheritable, else initial","Hides","Errors"],ans:1},
{id:163,topic:"CSS",level:"hard",q:"What does revert do?",opts:["Errors","Reverts to user-agent style","Hide","Inherits"],ans:1},
{id:164,topic:"CSS",level:"hard",q:"What is contain property used for?",opts:["Layout","Hints isolation for performance (paint, layout, size)","Wrapping","Animation"],ans:1},
{id:165,topic:"CSS",level:"hard",q:"clip-path property?",opts:["Hides","Clips element to a shape","Crops images","Sets aspect"],ans:1},
{id:166,topic:"CSS",level:"hard",q:"backdrop-filter affects?",opts:["Element itself","Area behind element (e.g. blur)","Border","Background colour"],ans:1},
{id:167,topic:"CSS",level:"hard",q:"filter:blur(5px) does?",opts:["Hides","Blurs the element visually","Cache","Effects on bg"],ans:1},
{id:168,topic:"CSS",level:"hard",q:"transform:scale(0.5) does?",opts:["Halves size","Doubles","Removes","Rotates"],ans:0},
{id:169,topic:"CSS",level:"hard",q:"transform:rotate(45deg) does?",opts:["Hide","Rotate by 45°","Tilt 45px","Scale"],ans:1},
{id:170,topic:"CSS",level:"hard",q:"transform:skew(20deg) does?",opts:["Hide","Skew along X axis","Rotate","Scale"],ans:1},
{id:171,topic:"CSS",level:"hard",q:"transform-origin sets?",opts:["Source","Pivot point for transforms","Final","Animation"],ans:1},
{id:172,topic:"CSS",level:"hard",q:"perspective property used for?",opts:["2D","3D depth — distance for 3D transformed children","Layout","Hide"],ans:1},
{id:173,topic:"CSS",level:"hard",q:"backface-visibility:hidden hides?",opts:["Element","Back of element when rotated 180","Border","Background"],ans:1},
{id:174,topic:"CSS",level:"hard",q:"Animation timing function 'ease-in-out' means?",opts:["Linear","Slow start, fast middle, slow end","Slow end","Fast start"],ans:1},
{id:175,topic:"CSS",level:"hard",q:"animation-fill-mode:forwards does?",opts:["Loops","Retains final keyframe styles after animation ends","Errors","Skips"],ans:1},
{id:176,topic:"CSS",level:"hard",q:"animation-iteration-count:infinite means?",opts:["Once","Loops forever","Never","Twice"],ans:1},
{id:177,topic:"CSS",level:"hard",q:"animation-direction:alternate does?",opts:["Reverse","Plays forwards then backwards alternately","Skips","Errors"],ans:1},
{id:178,topic:"CSS",level:"hard",q:"Logical property 'margin-inline' replaces?",opts:["margin-top","margin-left + margin-right","margin-bottom","margin shorthand"],ans:1},
{id:179,topic:"CSS",level:"hard",q:"Logical property 'margin-block' replaces?",opts:["margin-left/right","margin-top/bottom","margin","border"],ans:1},
{id:180,topic:"CSS",level:"hard",q:"What does light-dark() function do?",opts:["Colors","Picks colour based on color-scheme: light or dark","Filter","Animation"],ans:1},
{id:181,topic:"CSS",level:"hard",q:"What does color-scheme: light dark; do?",opts:["Both","Declares pages supports both light & dark schemes","Forces dark","Errors"],ans:1},
{id:182,topic:"CSS",level:"hard",q:"What is the @container query?",opts:["Container","Apply rules based on container size, not viewport","JS","Old"],ans:1},
{id:183,topic:"CSS",level:"hard",q:"What does scroll-behavior:smooth do?",opts:["Hide scroll","Smooth animated scrolling","Fast","No effect"],ans:1},
{id:184,topic:"CSS",level:"hard",q:"What does scroll-snap-type do?",opts:["Hide","Define snap behaviour for scroll container","Lock","Fixed"],ans:1},
{id:185,topic:"CSS",level:"hard",q:"What is the :placeholder-shown pseudo-class?",opts:["Selects placeholder","Selects input while placeholder is visible","Hides","Disabled"],ans:1},
{id:186,topic:"CSS",level:"hard",q:":empty selector matches?",opts:["Empty class","Element with no children/text","Hidden","null"],ans:1},
{id:187,topic:"CSS",level:"hard",q:"What does pointer-events:none do?",opts:["Hides","Disables mouse events on element","Disables","Reset"],ans:1},
{id:188,topic:"CSS",level:"hard",q:"What does user-select:none do?",opts:["Disable","Prevents text selection","Hides","Read-only"],ans:1},
{id:189,topic:"CSS",level:"hard",q:"What does will-change hint?",opts:["Reset","Tell browser an element will change (perf)","Animation","Force GPU"],ans:1},
{id:190,topic:"CSS",level:"hard",q:"Why prefer transform over top/left for animation?",opts:["Same","transform is GPU-accelerated; doesn't trigger layout","No diff","Older"],ans:1},
{id:191,topic:"CSS",level:"hard",q:"What is critical CSS?",opts:["Required CSS","Above-the-fold styles inlined for fast initial render","Old","CDN"],ans:1},
{id:192,topic:"CSS",level:"hard",q:"What's vmin?",opts:["1% of viewport min(width,height)","1% width","1% height","1em"],ans:0},
{id:193,topic:"CSS",level:"hard",q:"What's vmax?",opts:["1% of viewport max(width,height)","100%","1px","1em"],ans:0},
{id:194,topic:"CSS",level:"hard",q:"What's the difference between % and vh?",opts:["Same","% relative to parent, vh to viewport","Reversed","No diff"],ans:1},
{id:195,topic:"CSS",level:"hard",q:"What is the cascade?",opts:["Order","Algorithm picking style: origin, specificity, source order","Animation","CSS file"],ans:1},
{id:196,topic:"CSS",level:"hard",q:"In specificity, what counts more: class or attribute selector?",opts:["Class","Both same (0,1,0)","Attribute","Pseudo"],ans:1},
{id:197,topic:"CSS",level:"hard",q:"Which selector has 0 specificity?",opts:["* and pseudo-elements","#id","class","tag"],ans:0},
{id:198,topic:"CSS",level:"hard",q:"What is shadow piercing combinator ::part()?",opts:["Pseudo","Style exposed parts of Web Component's shadow DOM","Hide","Animation"],ans:1},
{id:199,topic:"CSS",level:"hard",q:"What is the float:inline-start?",opts:["Hide","Logical equivalent of float:left (LTR)","Replace","Animation"],ans:1},
{id:200,topic:"CSS",level:"hard",q:"What's @supports rule used for?",opts:["JS","Feature query for CSS support","Print","Variables"],ans:1}
];

// ============================================================
// JavaScript — extras  (target ~280 new → topic total ~400)
// ============================================================
const JS_EXTRA = [
// EASY
{id:121,topic:"JS",level:"easy",q:"Comment for multi-line in JS?",opts:["// ...","# ...","/* ... */","-- ..."],ans:2},
{id:122,topic:"JS",level:"easy",q:"How to convert number to string?",opts:["n.toString()","String(n)","''+n","All of the above"],ans:3},
{id:123,topic:"JS",level:"easy",q:"What does parseFloat('3.14abc') return?",opts:["NaN","3.14","3","Error"],ans:1},
{id:124,topic:"JS",level:"easy",q:"What does parseInt('10.5') return?",opts:["10.5","10","11","NaN"],ans:1},
{id:125,topic:"JS",level:"easy",q:"What's the result of '5'==5?",opts:["true","false","NaN","Error"],ans:0},
{id:126,topic:"JS",level:"easy",q:"What's the result of '5'===5?",opts:["true","false","NaN","Error"],ans:1},
{id:127,topic:"JS",level:"easy",q:"Result of Boolean(0)?",opts:["true","false","0","NaN"],ans:1},
{id:128,topic:"JS",level:"easy",q:"Result of Boolean('')?",opts:["true","false","Error","null"],ans:1},
{id:129,topic:"JS",level:"easy",q:"Result of Boolean('false')?",opts:["true","false","Error","null"],ans:0},
{id:130,topic:"JS",level:"easy",q:"How to create array literal?",opts:["new Array()","[1,2,3]","Array.from()","All work"],ans:3},
{id:131,topic:"JS",level:"easy",q:"How to access first array item?",opts:["a.first","a[0]","a.head","a.start"],ans:1},
{id:132,topic:"JS",level:"easy",q:"How to access last item without length?",opts:["a[-1]","a.last","a.at(-1)","a.end"],ans:2},
{id:133,topic:"JS",level:"easy",q:"What does .concat() do on arrays?",opts:["Sorts","Joins arrays into new array","Mutates","Hides"],ans:1},
{id:134,topic:"JS",level:"easy",q:"What does .slice(1,3) return?",opts:["Mutated","New array [1..2]","Mutates","First 3"],ans:1},
{id:135,topic:"JS",level:"easy",q:"What does .splice() do?",opts:["Pure","Mutates array (add/remove)","Sorts","Reverses"],ans:1},
{id:136,topic:"JS",level:"easy",q:"How to reverse array in-place?",opts:["a.reverse()","a.rev()","reverse(a)","a.flip()"],ans:0},
{id:137,topic:"JS",level:"easy",q:"How to sort array?",opts:["a.order()","a.sort()","sort(a)","a.arrange()"],ans:1},
{id:138,topic:"JS",level:"easy",q:"Default sort order?",opts:["Numeric","Lexicographic (string)","Random","Date"],ans:1},
{id:139,topic:"JS",level:"easy",q:"How to sort numbers ascending?",opts:["a.sort()","a.sort((x,y)=>x-y)","sort(a,asc)","a.numericSort()"],ans:1},
{id:140,topic:"JS",level:"easy",q:"How to convert array to string?",opts:["a.toString()","String(a)","a.join(',')","All work (similar)"],ans:3},
{id:141,topic:"JS",level:"easy",q:"How to check if value is array?",opts:["typeof a","Array.isArray(a)","instanceof Array","Both b and c"],ans:3},
{id:142,topic:"JS",level:"easy",q:"How to log multiple values?",opts:["console.log(a,b,c)","console.print()","console.show()","log()"],ans:0},
{id:143,topic:"JS",level:"easy",q:"How to log error?",opts:["console.error()","throw()","alert()","log.err()"],ans:0},
{id:144,topic:"JS",level:"easy",q:"How to clear console?",opts:["console.clear()","clear()","reset()","console.empty()"],ans:0},
{id:145,topic:"JS",level:"easy",q:"How to log time?",opts:["console.time('x')","Date.now()","time.log()","perf.now()"],ans:0},
// MEDIUM
{id:146,topic:"JS",level:"medium",q:"What is event bubbling?",opts:["Up","Event propagates from child to parent","Down","Stops"],ans:1},
{id:147,topic:"JS",level:"medium",q:"What is event capturing?",opts:["Down","Event goes parent→child first","Up","No diff"],ans:1},
{id:148,topic:"JS",level:"medium",q:"How to stop event propagation?",opts:["e.stop()","e.stopPropagation()","e.cancel()","return false in addEventListener"],ans:1},
{id:149,topic:"JS",level:"medium",q:"How to prevent default action?",opts:["e.prevent()","e.preventDefault()","e.stop()","return null"],ans:1},
{id:150,topic:"JS",level:"medium",q:"e.target vs e.currentTarget?",opts:["Same","target is actual clicked, currentTarget is handler-attached","Reversed","No diff"],ans:1},
{id:151,topic:"JS",level:"medium",q:"How to remove event listener?",opts:["removeEventListener with SAME function ref","off()","detach()","clear()"],ans:0},
{id:152,topic:"JS",level:"medium",q:"What does once:true option do?",opts:["Always","Listener auto-removes after first trigger","Never","Same"],ans:1},
{id:153,topic:"JS",level:"medium",q:"What does passive:true do (touch)?",opts:["Disables","Promises not to preventDefault → smoother scroll","Slows","Errors"],ans:1},
{id:154,topic:"JS",level:"medium",q:"How to add class to element?",opts:["el.class.add('x')","el.classList.add('x')","el.add('x')","el.className.push('x')"],ans:1},
{id:155,topic:"JS",level:"medium",q:"How to remove class?",opts:["el.classList.remove('x')","el.removeClass('x')","el.class.delete('x')","Both A and B"],ans:0},
{id:156,topic:"JS",level:"medium",q:"How to toggle class?",opts:["el.toggle('x')","el.classList.toggle('x')","el.switch('x')","el.flip('x')"],ans:1},
{id:157,topic:"JS",level:"medium",q:"How to check if has class?",opts:["el.has('x')","el.classList.contains('x')","el.is('x')","el.className=='x'"],ans:1},
{id:158,topic:"JS",level:"medium",q:"How to set attribute?",opts:["el.setAttribute('x','y')","el.attr('x','y')","el['x']='y'","All work for some"],ans:0},
{id:159,topic:"JS",level:"medium",q:"How to get attribute?",opts:["el.getAttribute('x')","el.attr('x')","el.get('x')","el['x']"],ans:0},
{id:160,topic:"JS",level:"medium",q:"How to create element?",opts:["document.create('div')","document.createElement('div')","new Element('div')","HTML('div')"],ans:1},
{id:161,topic:"JS",level:"medium",q:"How to append child?",opts:["parent.append(child)","parent.appendChild(child)","Both A and B","add()"],ans:2},
{id:162,topic:"JS",level:"medium",q:"How to remove element?",opts:["el.remove()","el.parent.removeChild(el)","Both work","delete el"],ans:2},
{id:163,topic:"JS",level:"medium",q:"How to replace element?",opts:["el.replace()","parent.replaceChild(new, old)","el.swap(new)","el = new"],ans:1},
{id:164,topic:"JS",level:"medium",q:"How to clone element (deep)?",opts:["el.clone()","el.cloneNode(true)","copy(el)","el.copy()"],ans:1},
{id:165,topic:"JS",level:"medium",q:"How to get computed style?",opts:["el.style","getComputedStyle(el)","el.css()","window.style(el)"],ans:1},
{id:166,topic:"JS",level:"medium",q:"el.style.color sets inline style?",opts:["No","Yes","Only class","Errors"],ans:1},
{id:167,topic:"JS",level:"medium",q:"What's the DOMContentLoaded event?",opts:["After CSS load","After HTML parsed (no wait for images)","After everything","Never"],ans:1},
{id:168,topic:"JS",level:"medium",q:"What's the load event?",opts:["After HTML","After ALL resources (images, css) loaded","Never","Same as DOMContentLoaded"],ans:1},
{id:169,topic:"JS",level:"medium",q:"What is localStorage scope?",opts:["Per tab","Per origin (persists across tabs/sessions)","Per session","Global"],ans:1},
{id:170,topic:"JS",level:"medium",q:"How to set localStorage?",opts:["localStorage.set()","localStorage.setItem(key, val)","ls.put()","localStorage[key]=val (also works)"],ans:1},
{id:171,topic:"JS",level:"medium",q:"How to get localStorage?",opts:["localStorage.get()","localStorage.getItem(key)","localStorage[key]","Both B and C"],ans:3},
{id:172,topic:"JS",level:"medium",q:"localStorage values are stored as?",opts:["Objects","Strings only","Any type","Numbers"],ans:1},
{id:173,topic:"JS",level:"medium",q:"How to store object in localStorage?",opts:["Direct set","JSON.stringify, then JSON.parse on read","Wrap","Errors"],ans:1},
{id:174,topic:"JS",level:"medium",q:"How to clear all localStorage?",opts:["localStorage.clear()","localStorage.empty()","localStorage.delete()","localStorage = null"],ans:0},
{id:175,topic:"JS",level:"medium",q:"What's the difference between localStorage and cookies?",opts:["Same","cookies sent to server, localStorage client-only","Reversed","Cookies larger"],ans:1},
{id:176,topic:"JS",level:"medium",q:"What does encodeURIComponent do?",opts:["Hashes","Escapes URI characters (?, &, =)","Lowercases","Compresses"],ans:1},
{id:177,topic:"JS",level:"medium",q:"What does JSON.stringify(undefined) return?",opts:["'undefined'","undefined","null","Error"],ans:1},
{id:178,topic:"JS",level:"medium",q:"What does JSON.stringify(NaN) return?",opts:["'NaN'","'null'","null","Error"],ans:1},
{id:179,topic:"JS",level:"medium",q:"What does JSON.stringify(function(){}) return?",opts:["String of fn","undefined","'function'","Error"],ans:1},
{id:180,topic:"JS",level:"medium",q:"How to deep clone object (simple)?",opts:["{...obj}","JSON.parse(JSON.stringify(obj))","Object.copy(obj)","Direct ="],ans:1},
{id:181,topic:"JS",level:"medium",q:"What's the limitation of JSON deep clone?",opts:["None","Loses functions, Dates become strings, no cycles","No","Lossless"],ans:1},
{id:182,topic:"JS",level:"medium",q:"What is structuredClone?",opts:["Same as JSON","Built-in deep clone supporting more types","Old","Library"],ans:1},
{id:183,topic:"JS",level:"medium",q:"What does new Date() return?",opts:["Date object representing now","String","Number","Error"],ans:0},
{id:184,topic:"JS",level:"medium",q:"How to get current timestamp?",opts:["Date.now()","new Date().getTime()","+new Date()","All work"],ans:3},
{id:185,topic:"JS",level:"medium",q:"What does .getMonth() return?",opts:["1-12","0-11","Name","Error"],ans:1},
{id:186,topic:"JS",level:"medium",q:"What does .toISOString() return?",opts:["Local","ISO 8601 UTC string","Locale","Numeric"],ans:1},
{id:187,topic:"JS",level:"medium",q:"How to format date locally?",opts:["d.toString()","d.toLocaleString()","format(d)","d.locale()"],ans:1},
{id:188,topic:"JS",level:"medium",q:"What does new Set() create?",opts:["Object","Set (unique values collection)","Map","Array"],ans:1},
{id:189,topic:"JS",level:"medium",q:"How to add to Set?",opts:["s.push","s.add(x)","s.append","s[]"],ans:1},
{id:190,topic:"JS",level:"medium",q:"How to check Set membership?",opts:["s.has(x)","s.contains(x)","x in s","s.find"],ans:0},
{id:191,topic:"JS",level:"medium",q:"How to convert Set to array?",opts:["[...s]","Array.from(s)","Both","s.toArray()"],ans:2},
{id:192,topic:"JS",level:"medium",q:"How to deduplicate array?",opts:["[...new Set(arr)]","arr.unique()","dedupe(arr)","arr.distinct()"],ans:0},
{id:193,topic:"JS",level:"medium",q:"How to create Map?",opts:["new Map()","{}","new Object()","Map()"],ans:0},
{id:194,topic:"JS",level:"medium",q:"How to set Map entry?",opts:["m[k]=v","m.set(k,v)","m.put(k,v)","m.add(k,v)"],ans:1},
{id:195,topic:"JS",level:"medium",q:"How to get Map entry?",opts:["m[k]","m.get(k)","m.find(k)","m.lookup(k)"],ans:1},
{id:196,topic:"JS",level:"medium",q:"Map keys can be?",opts:["Strings only","Any type","Numbers only","Symbols only"],ans:1},
{id:197,topic:"JS",level:"medium",q:"How to get Map size?",opts:["m.length","m.size","m.count","Object.keys(m).length"],ans:1},
{id:198,topic:"JS",level:"medium",q:"How to iterate Map?",opts:["for..in","for..of m.entries()","forEach","Both B and C"],ans:3},
{id:199,topic:"JS",level:"medium",q:"What does Number.isInteger(5.0) return?",opts:["true","false","NaN","Error"],ans:0},
{id:200,topic:"JS",level:"medium",q:"What does Number.isFinite(Infinity) return?",opts:["true","false","null","Error"],ans:1},
{id:201,topic:"JS",level:"medium",q:"What's Number.MAX_SAFE_INTEGER (approx)?",opts:["2^31","2^53 - 1","2^64","Infinity"],ans:1},
{id:202,topic:"JS",level:"medium",q:"What is BigInt?",opts:["Big number string","Native large-int type via 5n syntax","Library","Float"],ans:1},
{id:203,topic:"JS",level:"medium",q:"5n + 5 — error?",opts:["No","Yes (cannot mix BigInt+Number)","Returns 10","Returns 10n"],ans:1},
{id:204,topic:"JS",level:"medium",q:"What's the result: typeof Symbol()?",opts:["object","symbol","function","string"],ans:1},
{id:205,topic:"JS",level:"medium",q:"How to declare multiple vars in one line?",opts:["let a=1, b=2","let a,b=1,2","var a=1; b=2","All work"],ans:0},
{id:206,topic:"JS",level:"medium",q:"Output: console.log(typeof null === 'object')?",opts:["true","false","Error","null"],ans:0},
// HARD
{id:207,topic:"JS",level:"hard",q:"What is the temporal dead zone?",opts:["Old code","Period where let/const declared but not yet initialised","Future ES","Async wait"],ans:1},
{id:208,topic:"JS",level:"hard",q:"What's a Promise's three states?",opts:["pending/fulfilled/rejected","start/running/done","wait/ready/error","none"],ans:0},
{id:209,topic:"JS",level:"hard",q:"What does Promise.resolve(5).then(v=>v*2) yield in v?",opts:["10","Promise","5","Error"],ans:0},
{id:210,topic:"JS",level:"hard",q:"What does Promise.allSettled do?",opts:["Like all","Resolves to array of {status,value/reason} for all","Rejects fast","Race"],ans:1},
{id:211,topic:"JS",level:"hard",q:"What does Promise.any do?",opts:["First","First fulfilled (rejects only if all reject)","All","Race"],ans:1},
{id:212,topic:"JS",level:"hard",q:"async returns?",opts:["Value","Promise","Iterator","Generator"],ans:1},
{id:213,topic:"JS",level:"hard",q:"What does await null do?",opts:["Error","Awaits a resolved promise wrapping null","Hangs","Throws"],ans:1},
{id:214,topic:"JS",level:"hard",q:"What's the microtask queue?",opts:["Slow","Queue for promise then handlers, runs before next render","Same as setTimeout","Old"],ans:1},
{id:215,topic:"JS",level:"hard",q:"Difference: setTimeout vs queueMicrotask?",opts:["Same","queueMicrotask runs sooner (before next paint)","setTimeout faster","No diff"],ans:1},
{id:216,topic:"JS",level:"hard",q:"What is debouncing useful for?",opts:["Faster","Reducing rapid-fire calls (e.g., search input)","Slow","Animation"],ans:1},
{id:217,topic:"JS",level:"hard",q:"What is throttling useful for?",opts:["Errors","Limit rate of event handlers (e.g., scroll)","Animation","Cache"],ans:1},
{id:218,topic:"JS",level:"hard",q:"What is memoization?",opts:["Cache","Caching function results by input","Storage","Loop"],ans:1},
{id:219,topic:"JS",level:"hard",q:"What is partial application?",opts:["Whole","Fixing some args of a function, returning new fn","Currying same","Optional"],ans:1},
{id:220,topic:"JS",level:"hard",q:"What is currying?",opts:["Sort","f(a,b,c) → f(a)(b)(c) — chain of unary fns","Same as partial","Recursion"],ans:1},
{id:221,topic:"JS",level:"hard",q:"What does Function.prototype.bind return?",opts:["Result","New function with this fixed","Same fn","null"],ans:1},
{id:222,topic:"JS",level:"hard",q:"What's the diff: call vs apply?",opts:["Same","call uses args list, apply uses array","Apply faster","No diff"],ans:1},
{id:223,topic:"JS",level:"hard",q:"What is 'this' in strict mode global?",opts:["window","undefined","global","null"],ans:1},
{id:224,topic:"JS",level:"hard",q:"What does 'use strict' do?",opts:["Old code","Enable strict mode (errors on bad practices)","Disable","Cache"],ans:1},
{id:225,topic:"JS",level:"hard",q:"What does Object.freeze return?",opts:["new","Same obj, frozen","null","Errors"],ans:1},
{id:226,topic:"JS",level:"hard",q:"What does Object.isFrozen do?",opts:["Freezes","Checks if object is frozen","null","Errors"],ans:1},
{id:227,topic:"JS",level:"hard",q:"Object.freeze is shallow or deep?",opts:["Shallow","Deep","Either","Error"],ans:0},
{id:228,topic:"JS",level:"hard",q:"What does hasOwnProperty check?",opts:["Inherited","Own (non-inherited) property","Prototype","Always true"],ans:1},
{id:229,topic:"JS",level:"hard",q:"What does 'in' operator check?",opts:["Own","Own + inherited prop","Inherited","Never"],ans:1},
{id:230,topic:"JS",level:"hard",q:"What is Object.create(proto)?",opts:["Empty","Object with given prototype","null","Error"],ans:1},
{id:231,topic:"JS",level:"hard",q:"What's Object.getPrototypeOf(obj)?",opts:["Class","Returns __proto__","null","Error"],ans:1},
{id:232,topic:"JS",level:"hard",q:"What is the prototype chain?",opts:["Class","Chain via __proto__ for prop lookup","DOM","Closure"],ans:1},
{id:233,topic:"JS",level:"hard",q:"What does new keyword do?",opts:["Allocates","Creates obj, links prototype, calls fn, returns","Errors","Hides"],ans:1},
{id:234,topic:"JS",level:"hard",q:"Difference: function vs arrow function?",opts:["Same","Arrow has lexical this, no arguments, no constructor","Reversed","Speed"],ans:1},
{id:235,topic:"JS",level:"hard",q:"What does IIFE stand for?",opts:["Internal","Immediately Invoked Function Expression","Inner","Iterator"],ans:1},
{id:236,topic:"JS",level:"hard",q:"What is closure leakage?",opts:["Memory","Holding refs preventing GC of large objects","Animation","Bug"],ans:1},
{id:237,topic:"JS",level:"hard",q:"What is event delegation?",opts:["Old","Attach single handler on parent for many children","Bubble","No diff"],ans:1},
{id:238,topic:"JS",level:"hard",q:"Why prefer event delegation?",opts:["Slower","Fewer listeners, works for dynamic children","More memory","No reason"],ans:1},
{id:239,topic:"JS",level:"hard",q:"What's the spread operator on object?",opts:["{...obj} clones (shallow)","{...obj} deep clones","Same as Object.assign","Both A and C"],ans:3},
{id:240,topic:"JS",level:"hard",q:"What's destructuring with default?",opts:["{a=1}=obj","{a:1}=obj","[a=1]=arr","Both A and C"],ans:3},
{id:241,topic:"JS",level:"hard",q:"What's the rest parameter?",opts:["...args (collects rest of args)","Spread","Same as args","Optional"],ans:0},
{id:242,topic:"JS",level:"hard",q:"What is event.persist (in React legacy)?",opts:["No effect","Keep synthetic event for async use (pre-React 17)","Async","Skip"],ans:1},
{id:243,topic:"JS",level:"hard",q:"What's the difference between for..in and for..of?",opts:["Same","for..in iterates keys, for..of iterates values (iterables)","Reversed","Numeric"],ans:1},
{id:244,topic:"JS",level:"hard",q:"What's iterable protocol?",opts:["Has Symbol.iterator method","Has next","Has size","Has length"],ans:0},
{id:245,topic:"JS",level:"hard",q:"What does generator function syntax look like?",opts:["function gen(){}","function* gen(){}","async function gen(){}","gen()"],ans:1},
{id:246,topic:"JS",level:"hard",q:"What does yield in a generator do?",opts:["Returns","Pauses, returns value, can be resumed","Errors","Stops"],ans:1},
{id:247,topic:"JS",level:"hard",q:"What does generator.next() return?",opts:["Value","{value, done}","Boolean","Promise"],ans:1},
{id:248,topic:"JS",level:"hard",q:"What is the spread on Set: [...new Set([1,1,2])]?",opts:["[1,1,2]","[1,2]","new Set","Error"],ans:1},
{id:249,topic:"JS",level:"hard",q:"What is Object.fromEntries([['a',1]])?",opts:["{a:1}","[['a',1]]","Error","Array"],ans:0},
{id:250,topic:"JS",level:"hard",q:"What does Array.from('abc') return?",opts:["['abc']","['a','b','c']","'abc'","Error"],ans:1},
{id:251,topic:"JS",level:"hard",q:"What's the difference: Array(3) vs Array.from({length:3})?",opts:["Same","Array(3) sparse, Array.from creates dense [undefined×3]","Reversed","No diff"],ans:1},
{id:252,topic:"JS",level:"hard",q:"What does flat() do?",opts:["Sort","Flatten nested arrays by 1 level","Hide","Resize"],ans:1},
{id:253,topic:"JS",level:"hard",q:"What's the depth arg of flat?",opts:["No","flat(depth) flattens N levels (Infinity = all)","Always 1","Errors"],ans:1},
{id:254,topic:"JS",level:"hard",q:"What does flatMap do?",opts:["Random","map + flat(1)","Filter","Sort"],ans:1},
{id:255,topic:"JS",level:"hard",q:"What's the difference: error vs reject in Promise?",opts:["Same","throw inside .then auto-rejects; reject is explicit","Async","No diff"],ans:1},
{id:256,topic:"JS",level:"hard",q:"What does try/catch handle in async function?",opts:["Sync only","Both sync and awaited rejections","Nothing","Async only"],ans:1},
{id:257,topic:"JS",level:"hard",q:"What does Promise constructor's executor get?",opts:["Nothing","(resolve, reject) functions","One callback","Errors"],ans:1},
{id:258,topic:"JS",level:"hard",q:"What is a thenable?",opts:["Promise","Object with .then method (not necessarily Promise)","Same","Async"],ans:1},
{id:259,topic:"JS",level:"hard",q:"How does optional chaining handle method call?",opts:["fn?.()","fn?.call","fn||call","Errors"],ans:0},
{id:260,topic:"JS",level:"hard",q:"What does typeof of undeclared var throw?",opts:["Error","Returns 'undefined' (special-cased)","null","Throws"],ans:1},
{id:261,topic:"JS",level:"hard",q:"What is the difference between == null and === null?",opts:["Same","== null also matches undefined","No","Reversed"],ans:1},
{id:262,topic:"JS",level:"hard",q:"What does Object.defineProperty do?",opts:["Sets","Defines/modifies property with descriptor (enumerable/writable etc.)","Hide","Animation"],ans:1},
{id:263,topic:"JS",level:"hard",q:"What is a getter (in classes)?",opts:["fn","Property defined with get keyword, called like prop","setter","Field"],ans:1},
{id:264,topic:"JS",level:"hard",q:"What is a Proxy?",opts:["Network","Wrapper allowing custom behaviour for get/set/etc.","Cache","Cookie"],ans:1},
{id:265,topic:"JS",level:"hard",q:"What is Reflect?",opts:["Mirror","Built-in object with methods mirroring object operations","Util","Old"],ans:1},
{id:266,topic:"JS",level:"hard",q:"What does globalThis refer to?",opts:["window","Universal global object (window in browser, global in Node)","null","Same"],ans:1},
{id:267,topic:"JS",level:"hard",q:"What is dynamic import()?",opts:["Sync","Returns Promise, loads module on demand","Static","Errors"],ans:1},
{id:268,topic:"JS",level:"hard",q:"In modules, what's strict mode?",opts:["Off","Always on","Manual","No"],ans:1},
{id:269,topic:"JS",level:"hard",q:"Default export in ES module?",opts:["module.exports","export default x","export x","exports.default"],ans:1},
{id:270,topic:"JS",level:"hard",q:"Named import syntax?",opts:["import {x} from 'm'","import x from 'm'","require('m').x","import *"],ans:0},
{id:271,topic:"JS",level:"hard",q:"What does import * as m do?",opts:["Import all named exports as namespace m","Error","Default","Both"],ans:0},
{id:272,topic:"JS",level:"hard",q:"What's Hoisting limitation for let/const?",opts:["Same as var","Hoisted but in TDZ until declared","Not hoisted","Always"],ans:1},
{id:273,topic:"JS",level:"hard",q:"What does void 0 evaluate to?",opts:["null","undefined","0","Error"],ans:1},
{id:274,topic:"JS",level:"hard",q:"What's a tagged template literal?",opts:["Same","tag`text ${x}` — fn called with strings + values","Comment","CSS"],ans:1},
{id:275,topic:"JS",level:"hard",q:"What does Array.of(7) create?",opts:["[7]","[undef×7]","Error","[0,1,...,6]"],ans:0},
{id:276,topic:"JS",level:"hard",q:"What does new Array(7) create?",opts:["[7]","Sparse array length 7","Error","[]"],ans:1},
{id:277,topic:"JS",level:"hard",q:"WeakMap differs from Map how?",opts:["Same","Keys must be objects, weak (GC'able)","Values","Faster"],ans:1},
{id:278,topic:"JS",level:"hard",q:"WeakSet keys must be?",opts:["Strings","Objects","Numbers","Any"],ans:1},
{id:279,topic:"JS",level:"hard",q:"What is observable in JS (e.g. RxJS)?",opts:["Hidden","Push-based stream of values","Library","Promise"],ans:1},
{id:280,topic:"JS",level:"hard",q:"What is the difference: undeclared vs undefined?",opts:["Same","undeclared = not declared (ReferenceError); undefined = declared but no value","Reversed","No diff"],ans:1},
{id:281,topic:"JS",level:"hard",q:"What is hoisted: var, function declaration, class?",opts:["All","var (undef) + function (full); class is TDZ","None","Only var"],ans:1},
{id:282,topic:"JS",level:"hard",q:"What's the result: function foo(){return}() ?",opts:["undefined","Error","null","NaN"],ans:1},
{id:283,topic:"JS",level:"hard",q:"What does .at(-1) on array return?",opts:["First","Last item","Errors","null"],ans:1},
{id:284,topic:"JS",level:"hard",q:"What does findIndex return when no match?",opts:["null","undefined","-1","Error"],ans:2},
{id:285,topic:"JS",level:"hard",q:"What does Object.is(NaN, NaN) return?",opts:["true","false","Error","null"],ans:0},
{id:286,topic:"JS",level:"hard",q:"What does Object.is(+0, -0) return?",opts:["true","false","NaN","Error"],ans:1},
{id:287,topic:"JS",level:"hard",q:"What's the result of [1,2,3].reduce((a,b)=>a*b)?",opts:["6","123","0","Error"],ans:0},
{id:288,topic:"JS",level:"hard",q:"What's the result of [].reduce((a,b)=>a+b)?",opts:["0","null","TypeError (no init)","undefined"],ans:2},
{id:289,topic:"JS",level:"hard",q:"What's the result of [].reduce((a,b)=>a+b,0)?",opts:["0","null","Error","undefined"],ans:0},
{id:290,topic:"JS",level:"hard",q:"What does .some() do?",opts:["All","Returns true if any element passes","First","Sum"],ans:1},
{id:291,topic:"JS",level:"hard",q:"What does .every() do?",opts:["Some","Returns true if all elements pass","First","Last"],ans:1},
{id:292,topic:"JS",level:"hard",q:"What does .fill(0,2,4) do?",opts:["Append 0","Fills indexes [2,4) with 0","Hides","Errors"],ans:1},
{id:293,topic:"JS",level:"hard",q:"What does .copyWithin(0,3) do?",opts:["Copies","Copies sublist starting at index 3 → position 0 (in-place)","Errors","Hides"],ans:1},
{id:294,topic:"JS",level:"hard",q:"What is the result: typeof class{}?",opts:["class","object","function","undefined"],ans:2},
{id:295,topic:"JS",level:"hard",q:"In class, what's static?",opts:["Instance","Method/prop on class itself, not instances","Private","Frozen"],ans:1},
{id:296,topic:"JS",level:"hard",q:"In class, what's # prefix?",opts:["Comment","Private field","Static","Method"],ans:1},
{id:297,topic:"JS",level:"hard",q:"How to call parent class method in subclass?",opts:["parent.","super.method()","this.method","base.method"],ans:1},
{id:298,topic:"JS",level:"hard",q:"What does super() do in constructor?",opts:["Errors","Calls parent constructor (required before this)","Hides","Async"],ans:1},
{id:299,topic:"JS",level:"hard",q:"Class fields default values?",opts:["No","Yes (instance fields initialised in constructor)","Static","Error"],ans:1},
{id:300,topic:"JS",level:"hard",q:"What is method shorthand?",opts:["fn:function(){}","fn(){}","fn = ()=>{}","Same"],ans:1}
];

// ============================================================
// Python — extras  (target ~400 new → topic total ~550)
// ============================================================
const PY_EXTRA = [
// EASY
{id:151,topic:"PY",level:"easy",q:"What's len('hello')?",opts:["4","5","6","Error"],ans:1},
{id:152,topic:"PY",level:"easy",q:"What's len('')?",opts:["0","1","null","Error"],ans:0},
{id:153,topic:"PY",level:"easy",q:"How to concatenate strings?",opts:["s1.concat(s2)","s1+s2","s1.add(s2)","s1&&s2"],ans:1},
{id:154,topic:"PY",level:"easy",q:"How to repeat string 3 times?",opts:["s.repeat(3)","s*3","3*s","Both b and c"],ans:3},
{id:155,topic:"PY",level:"easy",q:"How to check if substring 'b' in 'abc'?",opts:["s.contains('b')","'b' in s","s.has('b')","'b' is in s"],ans:1},
{id:156,topic:"PY",level:"easy",q:"How to convert to lowercase?",opts:["s.lower()","s.toLower()","s.lowercase()","lower(s)"],ans:0},
{id:157,topic:"PY",level:"easy",q:"How to convert to uppercase?",opts:["s.upper()","s.upperCase()","upper(s)","s.UPPERCASE()"],ans:0},
{id:158,topic:"PY",level:"easy",q:"Method for title case?",opts:["s.title()","s.capitalize()","s.titleCase()","Both A and B (different)"],ans:3},
{id:159,topic:"PY",level:"easy",q:"What does s.startswith('a') return?",opts:["bool","string","int","Error"],ans:0},
{id:160,topic:"PY",level:"easy",q:"What does s.endswith('z') return?",opts:["bool","string","int","Error"],ans:0},
{id:161,topic:"PY",level:"easy",q:"How to check digit only?",opts:["s.isdigit()","s.isInt()","isNumber(s)","s.numeric()"],ans:0},
{id:162,topic:"PY",level:"easy",q:"How to check alpha only?",opts:["s.isalpha()","s.isLetter()","isChar(s)","s.alpha()"],ans:0},
{id:163,topic:"PY",level:"easy",q:"How to check alphanumeric?",opts:["s.isalnum()","s.isAlphaNum()","alnum(s)","s.an()"],ans:0},
{id:164,topic:"PY",level:"easy",q:"How to count occurrences in string?",opts:["s.count('a')","s.find('a')","s.index('a')","s.times('a')"],ans:0},
{id:165,topic:"PY",level:"easy",q:"What does s.index('x') return if not found?",opts:["-1","None","Raises ValueError","0"],ans:2},
{id:166,topic:"PY",level:"easy",q:"What does s.find('x') return if not found?",opts:["-1","None","Raises","0"],ans:0},
{id:167,topic:"PY",level:"easy",q:"How to pad string left with zeros?",opts:["s.zfill(5)","s.lzero(5)","pad(s,5)","s.pad('0',5)"],ans:0},
{id:168,topic:"PY",level:"easy",q:"How to center string in width?",opts:["s.center(20)","s.cnt(20)","center(s,20)","s.middle(20)"],ans:0},
{id:169,topic:"PY",level:"easy",q:"How to remove prefix from string (3.9+)?",opts:["s.removeprefix('x')","s.lstrip('x')","s.cut('x')","s-='x'"],ans:0},
{id:170,topic:"PY",level:"easy",q:"What's print(end='') for?",opts:["No newline","Empty print","Suffix","Error"],ans:0},
{id:171,topic:"PY",level:"easy",q:"What's print(sep=',') for?",opts:["Separator between multiple args","End character","Errors","No effect"],ans:0},
{id:172,topic:"PY",level:"easy",q:"What's True + True?",opts:["TrueTrue","2","Error","1"],ans:1},
{id:173,topic:"PY",level:"easy",q:"What's int(True)?",opts:["0","1","-1","Error"],ans:1},
{id:174,topic:"PY",level:"easy",q:"What's int(False)?",opts:["0","1","-1","Error"],ans:0},
{id:175,topic:"PY",level:"easy",q:"What's bool(None)?",opts:["True","False","Error","None"],ans:1},
{id:176,topic:"PY",level:"easy",q:"What does None mean?",opts:["Zero","Null value placeholder","False","Empty string"],ans:1},
{id:177,topic:"PY",level:"easy",q:"How to check if x is None?",opts:["x is None","x == None","x == null","None(x)"],ans:0},
{id:178,topic:"PY",level:"easy",q:"What does x = y do (when y is list)?",opts:["Copy","Reference (alias)","Deep copy","Errors"],ans:1},
{id:179,topic:"PY",level:"easy",q:"How to shallow copy a list?",opts:["l.copy()","list(l)","l[:]","All work"],ans:3},
{id:180,topic:"PY",level:"easy",q:"How to deep copy?",opts:["copy.deepcopy()","l.deepcopy()","deep(l)","l.clone()"],ans:0},
// MEDIUM
{id:181,topic:"PY",level:"medium",q:"Output of [1,2,3][1:]?",opts:["[1,2]","[2,3]","[1,2,3]","[3]"],ans:1},
{id:182,topic:"PY",level:"medium",q:"Output of [1,2,3,4][::-1]?",opts:["[4,3,2,1]","[1,2,3,4]","Error","[1]"],ans:0},
{id:183,topic:"PY",level:"medium",q:"Output of [1,2,3,4][::2]?",opts:["[2,4]","[1,3]","[1,2]","Error"],ans:1},
{id:184,topic:"PY",level:"medium",q:"Output of 'hello'[-2:]?",opts:["'he'","'ello'","'lo'","'o'"],ans:2},
{id:185,topic:"PY",level:"medium",q:"What does list(zip([1,2],[3,4],[5,6])) give?",opts:["[1,2,3,4,5,6]","[(1,3,5),(2,4,6)]","[[1,3,5],[2,4,6]]","Error"],ans:1},
{id:186,topic:"PY",level:"medium",q:"What does dict(zip(['a','b'],[1,2])) give?",opts:["{'a':1,'b':2}","[('a',1),('b',2)]","Error","{}"],ans:0},
{id:187,topic:"PY",level:"medium",q:"What's dict.items()?",opts:["Keys","View of (key,value) tuples","Values","Length"],ans:1},
{id:188,topic:"PY",level:"medium",q:"What's dict.update(other)?",opts:["Replace","Merge other into self","Errors","Copy"],ans:1},
{id:189,topic:"PY",level:"medium",q:"How to iterate dict keys?",opts:["for k in d","for k in d.keys()","Both work","Neither"],ans:2},
{id:190,topic:"PY",level:"medium",q:"How to iterate dict items?",opts:["for k,v in d.items()","for x in d","for x in d.items()","Both A and C"],ans:3},
{id:191,topic:"PY",level:"medium",q:"What's set.add(x)?",opts:["Add (no error on dup)","Errors","Remove","Replace"],ans:0},
{id:192,topic:"PY",level:"medium",q:"What's set.remove(x) when x absent?",opts:["No-op","KeyError","ValueError","Returns False"],ans:1},
{id:193,topic:"PY",level:"medium",q:"What's set.discard(x) when x absent?",opts:["No-op","KeyError","Error","Returns False"],ans:0},
{id:194,topic:"PY",level:"medium",q:"What's s1 | s2 on sets?",opts:["Intersection","Union","Difference","XOR"],ans:1},
{id:195,topic:"PY",level:"medium",q:"What's s1 & s2 on sets?",opts:["Union","Intersection","Difference","XOR"],ans:1},
{id:196,topic:"PY",level:"medium",q:"What's s1 - s2 on sets?",opts:["Union","Difference (s1 minus s2)","Intersection","Error"],ans:1},
{id:197,topic:"PY",level:"medium",q:"What's s1 ^ s2 on sets?",opts:["XOR (symmetric difference)","Union","Intersection","Error"],ans:0},
{id:198,topic:"PY",level:"medium",q:"What's frozenset?",opts:["Empty","Immutable set","Sorted","List"],ans:1},
{id:199,topic:"PY",level:"medium",q:"What's tuple unpacking: a,b = 1,2?",opts:["Error","a=1, b=2","[1,2]","(1,2)"],ans:1},
{id:200,topic:"PY",level:"medium",q:"How to swap via tuple?",opts:["x,y = y,x","swap(x,y)","x=y; y=x","x.swap(y)"],ans:0},
{id:201,topic:"PY",level:"medium",q:"What is *a in *a,b,c = [1,2,3,4]?",opts:["Multiplies","a captures [1,2], b=3, c=4","Errors","No"],ans:1},
{id:202,topic:"PY",level:"medium",q:"What is **kwargs in function def?",opts:["Multi positional","Dict of keyword args","Square","Error"],ans:1},
{id:203,topic:"PY",level:"medium",q:"How to call function with dict as kwargs?",opts:["f(d)","f(**d)","f(*d)","f(d=d)"],ans:1},
{id:204,topic:"PY",level:"medium",q:"How to call function with list as args?",opts:["f(l)","f(*l)","f(**l)","f(...l)"],ans:1},
{id:205,topic:"PY",level:"medium",q:"What's a lambda?",opts:["Anonymous function","Class","Module","List comp"],ans:0},
{id:206,topic:"PY",level:"medium",q:"Can lambda have multiple statements?",opts:["Yes","No — single expression only","Yes if separated","Sometimes"],ans:1},
{id:207,topic:"PY",level:"medium",q:"What does sorted(l, key=lambda x: x[1]) do?",opts:["Sort","Sort by second element of each item","Errors","Reverse"],ans:1},
{id:208,topic:"PY",level:"medium",q:"What does sorted(l, reverse=True) do?",opts:["Same","Sort descending","Error","Original"],ans:1},
{id:209,topic:"PY",level:"medium",q:"What's the difference l.sort() vs sorted(l)?",opts:["No","sort() in-place returns None; sorted returns new","Reversed","Same"],ans:1},
{id:210,topic:"PY",level:"medium",q:"What does map(f, [1,2]) return type?",opts:["list","map (iterator)","tuple","str"],ans:1},
{id:211,topic:"PY",level:"medium",q:"What does filter(f, [1,2]) return type?",opts:["list","filter (iterator)","tuple","Error"],ans:1},
{id:212,topic:"PY",level:"medium",q:"How to chain filter+map?",opts:["map(f, filter(g, l))","filter(map(...))","Both","Either"],ans:0},
{id:213,topic:"PY",level:"medium",q:"What's a list comprehension's general form?",opts:["[expr for x in iter if cond]","for [expr]","map [expr]","while [expr]"],ans:0},
{id:214,topic:"PY",level:"medium",q:"What's a generator expression?",opts:["(expr for x in iter) — lazy","List comp","Same","fn"],ans:0},
{id:215,topic:"PY",level:"medium",q:"Difference: [] vs () in comprehension?",opts:["Same","[] list, () generator","Reversed","No"],ans:1},
{id:216,topic:"PY",level:"medium",q:"What is next(iter)?",opts:["Skip","Get next value from iterator","Error","Length"],ans:1},
{id:217,topic:"PY",level:"medium",q:"What raises when generator exhausted?",opts:["Returns None","StopIteration","ValueError","Error"],ans:1},
{id:218,topic:"PY",level:"medium",q:"What's iter([1,2,3])?",opts:["Same list","Iterator object","Tuple","Error"],ans:1},
{id:219,topic:"PY",level:"medium",q:"What is yield?",opts:["Returns","Pauses generator, returns value","Errors","Skip"],ans:1},
{id:220,topic:"PY",level:"medium",q:"What's yield from?",opts:["Delegate to sub-generator","Same as yield","Error","Loop"],ans:0},
{id:221,topic:"PY",level:"medium",q:"What's @property decorator?",opts:["Read-only","Defines method that's called like a property","Set","Static"],ans:1},
{id:222,topic:"PY",level:"medium",q:"What's @staticmethod?",opts:["Class","Method bound to class — no self/cls","Instance","Private"],ans:1},
{id:223,topic:"PY",level:"medium",q:"What's @classmethod first arg?",opts:["self","cls (class itself)","this","obj"],ans:1},
{id:224,topic:"PY",level:"medium",q:"What's __init__?",opts:["Destructor","Constructor","Static","Class meta"],ans:1},
{id:225,topic:"PY",level:"medium",q:"What's __del__?",opts:["Constructor","Destructor (called when GC)","Static","Comparator"],ans:1},
{id:226,topic:"PY",level:"medium",q:"What's __str__?",opts:["For comparison","Used by str() / print()","For init","For iter"],ans:1},
{id:227,topic:"PY",level:"medium",q:"What's __repr__?",opts:["For str","For developer-friendly repr — repr() / debug","Init","Hash"],ans:1},
{id:228,topic:"PY",level:"medium",q:"What's __len__?",opts:["Hash","Used by len()","Length attr","Init"],ans:1},
{id:229,topic:"PY",level:"medium",q:"What's __eq__?",opts:["Hash","Used by ==","str","len"],ans:1},
{id:230,topic:"PY",level:"medium",q:"What's __hash__?",opts:["Used by hash() / sets/dict","str","len","init"],ans:0},
{id:231,topic:"PY",level:"medium",q:"What's __iter__?",opts:["Hash","Used by iter()/for loops","str","len"],ans:1},
{id:232,topic:"PY",level:"medium",q:"What's __next__?",opts:["Init","Used by next() — for iterators","str","len"],ans:1},
{id:233,topic:"PY",level:"medium",q:"What's __getitem__?",opts:["Used by obj[key]","Setter","init","len"],ans:0},
{id:234,topic:"PY",level:"medium",q:"What's __setitem__?",opts:["Getter","Used by obj[key]=v","init","del"],ans:1},
{id:235,topic:"PY",level:"medium",q:"What's __call__?",opts:["Init","Makes instance callable like fn","str","len"],ans:1},
{id:236,topic:"PY",level:"medium",q:"What's __enter__/__exit__?",opts:["Iter","Context manager protocol (with stmt)","Sort","Hash"],ans:1},
{id:237,topic:"PY",level:"medium",q:"What does 'with' statement guarantee?",opts:["Fast","Cleanup via __exit__ even on exception","Speed","None"],ans:1},
{id:238,topic:"PY",level:"medium",q:"What's contextlib?",opts:["No","Utils for context managers (e.g. @contextmanager)","Old","DB"],ans:1},
{id:239,topic:"PY",level:"medium",q:"What's a docstring?",opts:["Comment","String literal as first stmt in module/function/class — accessible via __doc__","Old","Type hint"],ans:1},
{id:240,topic:"PY",level:"medium",q:"How to get docstring of function f?",opts:["f.doc","f.__doc__","doc(f)","help(f)"],ans:1},
{id:241,topic:"PY",level:"medium",q:"How to get type of x?",opts:["typeof(x)","type(x)","x.type()","typename(x)"],ans:1},
{id:242,topic:"PY",level:"medium",q:"How to check instance of class?",opts:["x is A","isinstance(x, A)","x.is(A)","x.class==A"],ans:1},
{id:243,topic:"PY",level:"medium",q:"How to check subclass?",opts:["issubclass(B, A)","B is A","B.parent==A","B subof A"],ans:0},
{id:244,topic:"PY",level:"medium",q:"What is multiple inheritance?",opts:["Forbidden","Class inherits from multiple parents","Single only","Error"],ans:1},
{id:245,topic:"PY",level:"medium",q:"What's MRO?",opts:["Method Run Order","Method Resolution Order (C3 linearisation)","Module","Random"],ans:1},
{id:246,topic:"PY",level:"medium",q:"How to view MRO?",opts:["ClassName.__mro__","mro(ClassName)","Both","Neither"],ans:0},
{id:247,topic:"PY",level:"medium",q:"What's super().__init__()?",opts:["Calls parent's __init__","Same","Skip","Init self"],ans:0},
{id:248,topic:"PY",level:"medium",q:"What is abstract method?",opts:["Empty","Method declared in ABC; subclass must implement","Static","Final"],ans:1},
{id:249,topic:"PY",level:"medium",q:"How to declare abstract method?",opts:["@abstractmethod (from abc module)","abstract def","virtual def","def @abc"],ans:0},
{id:250,topic:"PY",level:"medium",q:"What's a metaclass?",opts:["Class of classes (default: type)","Old","Static","Module"],ans:0},
// HARD
{id:251,topic:"PY",level:"hard",q:"What does *args do in def f(*args)?",opts:["Single","Collects positional args into tuple","Spread","Kwargs"],ans:1},
{id:252,topic:"PY",level:"hard",q:"What does **kwargs do?",opts:["Collects keyword args into dict","Spread","List","Tuple"],ans:0},
{id:253,topic:"PY",level:"hard",q:"What's the order of arg types in def?",opts:["pos, *args, kwarg-only, **kwargs","kwargs first","random","No order"],ans:0},
{id:254,topic:"PY",level:"hard",q:"What's a positional-only parameter?",opts:["No","Before / in signature, can't be keyword-passed","Default","Optional"],ans:1},
{id:255,topic:"PY",level:"hard",q:"What's a keyword-only parameter?",opts:["After * in signature","Default","Required","Optional"],ans:0},
{id:256,topic:"PY",level:"hard",q:"What's a closure in Python?",opts:["Loop","Inner fn capturing outer's vars","Class","Decorator"],ans:1},
{id:257,topic:"PY",level:"hard",q:"What does nonlocal do?",opts:["Global","Refer to enclosing (non-global) scope var","Local","Static"],ans:1},
{id:258,topic:"PY",level:"hard",q:"Output of: x=1\\ndef f(): x=2\\nf()\\nprint(x)?",opts:["1","2","Error","None"],ans:0},
{id:259,topic:"PY",level:"hard",q:"What's mutable default arg gotcha?",opts:["No issue","Default created ONCE; shared between calls","Each call new","Error"],ans:1},
{id:260,topic:"PY",level:"hard",q:"How to safely default mutable arg?",opts:["def f(x=[])","def f(x=None): x=x or []","No way","def f(x=mutable)"],ans:1},
{id:261,topic:"PY",level:"hard",q:"What does id(x) return?",opts:["Name","Identity (memory addr in CPython)","Hash","Type"],ans:1},
{id:262,topic:"PY",level:"hard",q:"What does hash(x) require?",opts:["Mutable","x must be hashable (immutable typically)","List","Errors"],ans:1},
{id:263,topic:"PY",level:"hard",q:"Are lists hashable?",opts:["Yes","No (mutable)","Sometimes","Always"],ans:1},
{id:264,topic:"PY",level:"hard",q:"Are tuples always hashable?",opts:["Yes","Only if all elements hashable","No","Sometimes"],ans:1},
{id:265,topic:"PY",level:"hard",q:"What's a frozen dataclass?",opts:["Slow","Immutable dataclass (frozen=True)","Error","Old"],ans:1},
{id:266,topic:"PY",level:"hard",q:"What's @dataclass?",opts:["Old","Auto-generates __init__/__repr__/__eq__ from fields","Slow","Errors"],ans:1},
{id:267,topic:"PY",level:"hard",q:"How to type-annotate a function arg?",opts:["def f(x:int):","def f(x as int)","def f(int x)","def f(x=int)"],ans:0},
{id:268,topic:"PY",level:"hard",q:"How to annotate return type?",opts:["def f() returns int:","def f() -> int:","def f(): int","def f() => int"],ans:1},
{id:269,topic:"PY",level:"hard",q:"Are type hints enforced at runtime?",opts:["Yes","No (hints only)","Sometimes","Errors"],ans:1},
{id:270,topic:"PY",level:"hard",q:"What is typing.Optional[int]?",opts:["int|None","int only","List[int]","Error"],ans:0},
{id:271,topic:"PY",level:"hard",q:"What is List[int] from typing?",opts:["Same as list","Generic list[int] (Python 3.9+: list[int] directly)","Tuple","Error"],ans:1},
{id:272,topic:"PY",level:"hard",q:"What is f-string formatting?",opts:["Old","f'{x}' — interpolated","format()","%"],ans:1},
{id:273,topic:"PY",level:"hard",q:"f'{x:.2f}' formats x as?",opts:["2 decimal float","2 digits","2 chars","Error"],ans:0},
{id:274,topic:"PY",level:"hard",q:"f'{x:>10}' formats?",opts:["Pad","Right-align in width 10","Left-align","Center"],ans:1},
{id:275,topic:"PY",level:"hard",q:"f'{x:0>5}' formats?",opts:["Pad with 0 left, width 5","Right pad","Error","Zfill"],ans:0},
{id:276,topic:"PY",level:"hard",q:"What's the walrus operator :=?",opts:["Old","Assignment expression — assign and use in same expr","Hash","Decorator"],ans:1},
{id:277,topic:"PY",level:"hard",q:"What does 'match-case' do (3.10+)?",opts:["Loop","Structural pattern matching","Switch","Try"],ans:1},
{id:278,topic:"PY",level:"hard",q:"What is del?",opts:["Hide","Removes binding/item","Error","Trash"],ans:1},
{id:279,topic:"PY",level:"hard",q:"What is global statement for?",opts:["Imports","Declare assignment refers to module-level var","Local","No"],ans:1},
{id:280,topic:"PY",level:"hard",q:"What does assert do?",opts:["Always run","Errors if condition False (when -O not set)","Comment","Hide"],ans:1},
{id:281,topic:"PY",level:"hard",q:"What raises AssertionError?",opts:["assert False","raise AssertionError","Both","Just print"],ans:2},
{id:282,topic:"PY",level:"hard",q:"What's try/except/else?",opts:["No else","else runs if no exception","else always","Errors"],ans:1},
{id:283,topic:"PY",level:"hard",q:"What's finally guaranteed?",opts:["Sometimes","Always runs (success or exception)","Only error","Skip"],ans:1},
{id:284,topic:"PY",level:"hard",q:"How to catch multiple exceptions?",opts:["except A, B:","except (A,B):","try multi","except A; except B"],ans:1},
{id:285,topic:"PY",level:"hard",q:"How to access caught exception?",opts:["except E as e:","except E e:","except E:e:","except(e):"],ans:0},
{id:286,topic:"PY",level:"hard",q:"How to re-raise the current exception?",opts:["raise","raise e","throw","retry"],ans:0},
{id:287,topic:"PY",level:"hard",q:"What's a custom exception?",opts:["Function","class MyError(Exception): pass","Decorator","Module"],ans:1},
{id:288,topic:"PY",level:"hard",q:"What is the EAFP principle?",opts:["Error","Easier to Ask Forgiveness than Permission (try/except first)","Slow","Old"],ans:1},
{id:289,topic:"PY",level:"hard",q:"What is LBYL?",opts:["Look Before You Leap (check first)","Library","Loop","Var"],ans:0},
{id:290,topic:"PY",level:"hard",q:"What's pickle module for?",opts:["Compress","Serialise Python objects to bytes","JSON","Hash"],ans:1},
{id:291,topic:"PY",level:"hard",q:"What's pickle's risk?",opts:["Fast","Loading untrusted pickle can run arbitrary code","Slow","Big"],ans:1},
{id:292,topic:"PY",level:"hard",q:"What's the difference: pickle vs json?",opts:["Same","pickle Python-specific binary; json text, cross-lang","Reversed","No"],ans:1},
{id:293,topic:"PY",level:"hard",q:"What does os.path.join do?",opts:["Concats with OS separator","Always /","Just text","Errors"],ans:0},
{id:294,topic:"PY",level:"hard",q:"What's pathlib.Path used for?",opts:["File","Object-oriented filesystem path manipulation","DB","Net"],ans:1},
{id:295,topic:"PY",level:"hard",q:"How to read all lines from file?",opts:["f.read()","f.readlines()","f.read().splitlines()","Both B and C"],ans:3},
{id:296,topic:"PY",level:"hard",q:"How to iterate file line by line?",opts:["for line in f","f.iter()","f.lines()","f.foreach"],ans:0},
{id:297,topic:"PY",level:"hard",q:"What does open's 'x' mode do?",opts:["Same as w","Exclusive: fails if file exists","Append","Read"],ans:1},
{id:298,topic:"PY",level:"hard",q:"What does 'b' suffix in mode mean?",opts:["Backup","Binary mode","Big","Background"],ans:1},
{id:299,topic:"PY",level:"hard",q:"How to specify encoding when opening?",opts:["open(f, encoding='utf-8')","open(f, 'utf-8')","f.encoding=...","No way"],ans:0},
{id:300,topic:"PY",level:"hard",q:"What is csv.DictReader?",opts:["List","Yields each row as dict (header-based)","Tuple","Bytes"],ans:1},
{id:301,topic:"PY",level:"hard",q:"What is csv.writer's writerow vs writerows?",opts:["Same","writerow=1 row, writerows=multiple","Reversed","No diff"],ans:1},
{id:302,topic:"PY",level:"hard",q:"How to make a random int 1-10?",opts:["random.int(1,10)","random.randint(1,10)","randint(1,10)","rand(1,10)"],ans:1},
{id:303,topic:"PY",level:"hard",q:"random.randint(a,b) — inclusive?",opts:["Exclusive","Inclusive on both","Exclusive on b","Exclusive on a"],ans:1},
{id:304,topic:"PY",level:"hard",q:"random.random() returns?",opts:["int","float in [0,1)","int 0-10","Error"],ans:1},
{id:305,topic:"PY",level:"hard",q:"random.choice([1,2,3])?",opts:["1","Random one of them","All","Error"],ans:1},
{id:306,topic:"PY",level:"hard",q:"random.shuffle(l)?",opts:["Returns new","In-place shuffle (returns None)","Errors","Copy"],ans:1},
{id:307,topic:"PY",level:"hard",q:"random.sample(l, k)?",opts:["Replace","k unique items from l","Mut","Same"],ans:1},
{id:308,topic:"PY",level:"hard",q:"How to seed random?",opts:["random.seed(42)","seed(42)","random.set(42)","random.start(42)"],ans:0},
{id:309,topic:"PY",level:"hard",q:"What's math.pi (approx)?",opts:["3.0","3.14159…","Error","22/7"],ans:1},
{id:310,topic:"PY",level:"hard",q:"What's math.sqrt(16)?",opts:["4","4.0","8","Error"],ans:1},
{id:311,topic:"PY",level:"hard",q:"What's math.floor(2.9)?",opts:["3","2","2.9","Error"],ans:1},
{id:312,topic:"PY",level:"hard",q:"What's math.ceil(2.1)?",opts:["2","3","2.1","Error"],ans:1},
{id:313,topic:"PY",level:"hard",q:"What's math.gcd(12,18)?",opts:["6","2","12","Error"],ans:0},
{id:314,topic:"PY",level:"hard",q:"What's datetime.datetime.now()?",opts:["str","Current local datetime","UTC","Error"],ans:1},
{id:315,topic:"PY",level:"hard",q:"How to format datetime?",opts:["dt.format()","dt.strftime('%Y-%m-%d')","dt.toStr()","str(dt)"],ans:1},
{id:316,topic:"PY",level:"hard",q:"How to parse string to datetime?",opts:["datetime.strptime(s,fmt)","datetime.parse(s)","datetime(s)","str.to_date()"],ans:0},
{id:317,topic:"PY",level:"hard",q:"What's timedelta?",opts:["Time","Difference of two datetimes","Now","Error"],ans:1},
{id:318,topic:"PY",level:"hard",q:"How to add 5 days to now?",opts:["now+5","now+timedelta(days=5)","now.add(5)","now.plus(5d)"],ans:1},
{id:319,topic:"PY",level:"hard",q:"What's os module for?",opts:["GUI","OS-level ops (env, paths, exec)","Network","File only"],ans:1},
{id:320,topic:"PY",level:"hard",q:"os.getcwd() returns?",opts:["Home","Current working directory","Root","Error"],ans:1},
{id:321,topic:"PY",level:"hard",q:"os.listdir(path) returns?",opts:["Iter","List of entries","Tuple","Error"],ans:1},
{id:322,topic:"PY",level:"hard",q:"os.path.exists(p)?",opts:["bool","str","int","Error"],ans:0},
{id:323,topic:"PY",level:"hard",q:"os.makedirs(p, exist_ok=True)?",opts:["Errors if exists","Creates recursively, OK if exists","No","Removes"],ans:1},
{id:324,topic:"PY",level:"hard",q:"sys.argv[0] is?",opts:["First arg","Script name","Last","Error"],ans:1},
{id:325,topic:"PY",level:"hard",q:"sys.argv[1:] is?",opts:["Empty","User-provided CLI args","All","Error"],ans:1},
{id:326,topic:"PY",level:"hard",q:"sys.exit(0) does?",opts:["No","Exits successfully","Errors","Print"],ans:1},
{id:327,topic:"PY",level:"hard",q:"What's __name__ == '__main__' for?",opts:["Always","Run code only when file is executed directly","Module","Imported"],ans:1},
{id:328,topic:"PY",level:"hard",q:"What does enum module provide?",opts:["Set","Enumerated symbolic names (class Color(Enum))","Iter","List"],ans:1},
{id:329,topic:"PY",level:"hard",q:"What is collections.Counter?",opts:["Map","Dict subclass counting hashables","Iter","Math"],ans:1},
{id:330,topic:"PY",level:"hard",q:"Counter([1,1,2,3]).most_common(1)?",opts:["[(1,2)]","[(1,1)]","[1,1]","Error"],ans:0},
{id:331,topic:"PY",level:"hard",q:"What is collections.defaultdict?",opts:["Dict","Dict with default factory for missing keys","Set","List"],ans:1},
{id:332,topic:"PY",level:"hard",q:"What is collections.OrderedDict (3.7+)?",opts:["Old","Same as dict (insertion order preserved natively)","Sorted","Hash"],ans:1},
{id:333,topic:"PY",level:"hard",q:"What is collections.deque?",opts:["List","Double-ended queue O(1) ends","Stack","Map"],ans:1},
{id:334,topic:"PY",level:"hard",q:"What is collections.namedtuple?",opts:["Tuple","Tuple subclass with named fields","Dict","Class"],ans:1},
{id:335,topic:"PY",level:"hard",q:"How to spawn a thread?",opts:["thread.start()","threading.Thread(target=f).start()","spawn(f)","async f()"],ans:1},
{id:336,topic:"PY",level:"hard",q:"What is GIL?",opts:["Lib","Global Interpreter Lock — one thread executes Python bytecode at a time","File","Memory"],ans:1},
{id:337,topic:"PY",level:"hard",q:"GIL impact for CPU-bound multithreaded?",opts:["Fast","Limited parallelism — use multiprocessing","No","Doubles"],ans:1},
{id:338,topic:"PY",level:"hard",q:"What is multiprocessing module for?",opts:["Thread","True parallel processes (separate interpreters)","Async","RPC"],ans:1},
{id:339,topic:"PY",level:"hard",q:"What is asyncio?",opts:["Threads","Cooperative async I/O (event loop)","Multi-CPU","Network"],ans:1},
{id:340,topic:"PY",level:"hard",q:"async def + await:?",opts:["Same as fn","Coroutine — await pauses cooperatively","Thread","Forks"],ans:1},
{id:341,topic:"PY",level:"hard",q:"What does asyncio.run(coro) do?",opts:["Background","Runs coroutine on event loop until complete","Thread","No"],ans:1},
{id:342,topic:"PY",level:"hard",q:"What's await for?",opts:["sleep","Suspends coroutine waiting for awaitable","Returns","Iterates"],ans:1},
{id:343,topic:"PY",level:"hard",q:"What is concurrent.futures.ThreadPoolExecutor?",opts:["Old","Reusable worker thread pool","Thread","CPU"],ans:1},
{id:344,topic:"PY",level:"hard",q:"What's a generator's send method?",opts:["Returns","Sends value INTO generator (replaces yield expr)","Errors","Skip"],ans:1},
{id:345,topic:"PY",level:"hard",q:"What's generator.close()?",opts:["Done","Stops generator (raises GeneratorExit inside)","Error","Continue"],ans:1},
{id:346,topic:"PY",level:"hard",q:"What's the OOP 4 pillars?",opts:["Inh, Encaps, Poly, Abst","Class, Obj, Method, Var","Function, Loop, If, Var","File, Net, DB, Loop"],ans:0},
{id:347,topic:"PY",level:"hard",q:"What's encapsulation in Python (convention)?",opts:["Strict private","Underscore prefix _name (weak) or __name (mangled)","Always public","Final"],ans:1},
{id:348,topic:"PY",level:"hard",q:"What's name mangling for __name?",opts:["No","Python rewrites to _ClassName__name","Pure private","Errors"],ans:1},
{id:349,topic:"PY",level:"hard",q:"What's polymorphism in Python?",opts:["Many","Same interface, different behaviour (duck typing)","Pointer","Class"],ans:1},
{id:350,topic:"PY",level:"hard",q:"What's duck typing?",opts:["Animal","'If it quacks like a duck' — behaviour matters, not type","Lib","String"],ans:1},
{id:351,topic:"PY",level:"hard",q:"What does isinstance(x, (int,float))?",opts:["int OR float","int AND float","Error","First"],ans:0},
{id:352,topic:"PY",level:"hard",q:"Output: print(0.1+0.2 == 0.3)?",opts:["True","False","Error","None"],ans:1},
{id:353,topic:"PY",level:"hard",q:"How to compare floats safely?",opts:["==","math.isclose(a,b)","abs(a-b)<1e-9","Both B and C"],ans:3},
{id:354,topic:"PY",level:"hard",q:"What is from __future__ import?",opts:["Time","Use upcoming Python features in current version","Library","Module"],ans:1},
{id:355,topic:"PY",level:"hard",q:"What is __pycache__?",opts:["Doc","Compiled bytecode (.pyc) cache","File","Cache"],ans:1},
{id:356,topic:"PY",level:"hard",q:"What is .pyi file?",opts:["Same as .py","Type stub file","Test","Doc"],ans:1},
{id:357,topic:"PY",level:"hard",q:"What's pip?",opts:["Library","Package installer for Python","Module","Interpreter"],ans:1},
{id:358,topic:"PY",level:"hard",q:"What does pip install -r requirements.txt do?",opts:["Update","Install all packages listed in file","Remove","List"],ans:1},
{id:359,topic:"PY",level:"hard",q:"What's a virtual environment?",opts:["VM","Isolated Python env (own packages)","Container","VM"],ans:1},
{id:360,topic:"PY",level:"hard",q:"How to create venv?",opts:["python -m venv myenv","virtual env","venv create","conda create"],ans:0},
{id:361,topic:"PY",level:"hard",q:"What does pip freeze output?",opts:["Errors","Installed packages with versions","Removes","Cache"],ans:1},
{id:362,topic:"PY",level:"hard",q:"What is PEP 8?",opts:["Lib","Style guide for Python code","Module","Test"],ans:1},
{id:363,topic:"PY",level:"hard",q:"What's PEP 20?",opts:["Test","Zen of Python (import this)","Style","Build"],ans:1},
{id:364,topic:"PY",level:"hard",q:"What does import this do?",opts:["Imports","Prints Zen of Python","Errors","Hides"],ans:1},
{id:365,topic:"PY",level:"hard",q:"What is the stack data structure?",opts:["FIFO","LIFO","Random","Sorted"],ans:1},
{id:366,topic:"PY",level:"hard",q:"How to implement stack via list?",opts:["append/pop","insert/pop(0)","push/shift","Both A and B work"],ans:0},
{id:367,topic:"PY",level:"hard",q:"How to implement queue (efficient)?",opts:["List","collections.deque","Tuple","Set"],ans:1},
{id:368,topic:"PY",level:"hard",q:"What is recursion base case?",opts:["Loop","Condition stopping recursion","Else","First"],ans:1},
{id:369,topic:"PY",level:"hard",q:"What is tail recursion?",opts:["Slow","Recursive call is last operation","Skip","Loop"],ans:1},
{id:370,topic:"PY",level:"hard",q:"Does Python optimize tail recursion?",opts:["Yes","No (RecursionError on deep)","Sometimes","Always"],ans:1},
{id:371,topic:"PY",level:"hard",q:"What is sys.setrecursionlimit for?",opts:["Same","Change Python recursion depth limit","Memory","Speed"],ans:1},
{id:372,topic:"PY",level:"hard",q:"What is a linked list?",opts:["Array","Nodes with data and next pointer","Hash","Tree"],ans:1},
{id:373,topic:"PY",level:"hard",q:"Big-O of list.append in Python?",opts:["O(n)","O(1) amortized","O(log n)","O(n²)"],ans:1},
{id:374,topic:"PY",level:"hard",q:"Big-O of list.insert(0, x)?",opts:["O(1)","O(n)","O(log n)","O(n²)"],ans:1},
{id:375,topic:"PY",level:"hard",q:"Big-O of dict[key] access?",opts:["O(1) average","O(n)","O(log n)","O(n²)"],ans:0},
{id:376,topic:"PY",level:"hard",q:"Big-O of 'in' on list?",opts:["O(1)","O(n)","O(log n)","O(n²)"],ans:1},
{id:377,topic:"PY",level:"hard",q:"Big-O of 'in' on set?",opts:["O(1) average","O(n)","O(log n)","O(n²)"],ans:0},
{id:378,topic:"PY",level:"hard",q:"How to time a code block?",opts:["time.time() diff","timeit module","Both","print"],ans:2},
{id:379,topic:"PY",level:"hard",q:"What is logging module for?",opts:["Print","Configurable logging (levels, handlers)","DB","Test"],ans:1},
{id:380,topic:"PY",level:"hard",q:"Log levels (low → high)?",opts:["DEBUG, INFO, WARNING, ERROR, CRITICAL","INFO, DEBUG","Random","Same"],ans:0},
{id:381,topic:"PY",level:"hard",q:"What does logging.basicConfig do?",opts:["Hides","Sets default config (format/level/handler)","Errors","Removes"],ans:1},
{id:382,topic:"PY",level:"hard",q:"What is sqlite3 module?",opts:["Network","Bundled SQLite DB client","DB lib","ORM"],ans:1},
{id:383,topic:"PY",level:"hard",q:"How to connect sqlite3?",opts:["sqlite.connect","sqlite3.connect('db.sqlite')","new sqlite()","import db"],ans:1},
{id:384,topic:"PY",level:"hard",q:"How to execute SQL?",opts:["cursor.run","cursor.execute(sql,params)","db.sql()","db.query()"],ans:1},
{id:385,topic:"PY",level:"hard",q:"How to commit a transaction?",opts:["cursor.commit","conn.commit()","commit()","auto"],ans:1},
{id:386,topic:"PY",level:"hard",q:"What is requests library?",opts:["Std","Third-party HTTP client (pip install)","Built-in","Async"],ans:1},
{id:387,topic:"PY",level:"hard",q:"How to GET via requests?",opts:["requests.fetch(url)","requests.get(url)","requests.send(url)","http.get(url)"],ans:1},
{id:388,topic:"PY",level:"hard",q:"How to read JSON from response?",opts:["r.json_body","r.json()","json(r)","r.text.json()"],ans:1},
{id:389,topic:"PY",level:"hard",q:"What is virtualenv?",opts:["Module","Tool creating isolated Python envs","Conda","Lib"],ans:1},
{id:390,topic:"PY",level:"hard",q:"What does string.format() do?",opts:["Hash","Replaces {} placeholders with args","Error","Skip"],ans:1},
{id:391,topic:"PY",level:"hard",q:"What's the % formatting?",opts:["Mod","Old-style string format: '%d' % 5","Hash","Errors"],ans:1},
{id:392,topic:"PY",level:"hard",q:"What's a context manager via @contextmanager decorator?",opts:["No","Generator that yields once, before=__enter__, after=__exit__","Test","Cache"],ans:1},
{id:393,topic:"PY",level:"hard",q:"What is __slots__?",opts:["Optimization: limit instance attrs to listed, save memory","Static","Public","Comment"],ans:0},
{id:394,topic:"PY",level:"hard",q:"What does property setter look like?",opts:["@prop.setter","@property.setter","Both A and B","No setter"],ans:0},
{id:395,topic:"PY",level:"hard",q:"What is bool subclass of?",opts:["int (True=1, False=0)","str","object","float"],ans:0},
{id:396,topic:"PY",level:"hard",q:"isinstance(True, int)?",opts:["False","True","Error","None"],ans:1},
{id:397,topic:"PY",level:"hard",q:"What is the difference: == vs is for small ints?",opts:["No","is may be True due to interning (-5..256)","Reversed","Always"],ans:1},
{id:398,topic:"PY",level:"hard",q:"What's the result of [] == []?",opts:["True","False","Error","None"],ans:0},
{id:399,topic:"PY",level:"hard",q:"What's the result of [] is []?",opts:["True","False","Error","None"],ans:1},
{id:400,topic:"PY",level:"hard",q:"What's the result of bool([0])?",opts:["False","True","0","None"],ans:1},
{id:401,topic:"PY",level:"hard",q:"What's 'x' if cond else 'y' called?",opts:["Switch","Conditional expression (ternary)","If","Lambda"],ans:1},
{id:402,topic:"PY",level:"hard",q:"What does next(iter([])) raise?",opts:["No","StopIteration","ValueError","Returns None"],ans:1},
{id:403,topic:"PY",level:"hard",q:"How to provide default to next?",opts:["next(it, default)","next(it)||default","try next","No way"],ans:0},
{id:404,topic:"PY",level:"hard",q:"What's the @functools.lru_cache?",opts:["Old","Memoise function results","Logger","Test"],ans:1},
{id:405,topic:"PY",level:"hard",q:"What's @functools.wraps?",opts:["Old","Preserve metadata of wrapped function in decorator","Hide","Log"],ans:1},
{id:406,topic:"PY",level:"hard",q:"What is itertools.chain?",opts:["Hash","Concatenates iterables lazily","Set","Map"],ans:1},
{id:407,topic:"PY",level:"hard",q:"What is itertools.cycle?",opts:["List","Repeats iterable forever","Hash","Random"],ans:1},
{id:408,topic:"PY",level:"hard",q:"What is itertools.combinations?",opts:["Pairs","All r-length combinations from iterable","Permutations","Maps"],ans:1},
{id:409,topic:"PY",level:"hard",q:"What is itertools.permutations?",opts:["Comb","All r-length orderings","Sort","Hash"],ans:1},
{id:410,topic:"PY",level:"hard",q:"What is itertools.product?",opts:["Multiply","Cartesian product","Permute","Combine"],ans:1},
{id:411,topic:"PY",level:"hard",q:"What is functools.reduce?",opts:["Sum","Apply function cumulatively to iterable","Filter","Map"],ans:1},
{id:412,topic:"PY",level:"hard",q:"What's the difference between iterable and iterator?",opts:["Same","Iterable: has __iter__; Iterator: has __next__ + __iter__","Reversed","No"],ans:1},
{id:413,topic:"PY",level:"hard",q:"How to create infinite iterator?",opts:["Loop","itertools.count(start)","Lambda","Yield"],ans:1},
{id:414,topic:"PY",level:"hard",q:"What is islice useful for?",opts:["Slow","Slicing iterators (can't [] iterators)","Error","Lazy"],ans:1},
{id:415,topic:"PY",level:"hard",q:"How to round half to even (banker's)?",opts:["round() does this by default","math.round","custom","ceil"],ans:0},
{id:416,topic:"PY",level:"hard",q:"What is divmod(a,b)?",opts:["(a//b, a%b)","[a,b]","Tuple of mods","Errors"],ans:0},
{id:417,topic:"PY",level:"hard",q:"What is bin(10)?",opts:["'10'","'0b1010'","1010","Error"],ans:1},
{id:418,topic:"PY",level:"hard",q:"What is hex(255)?",opts:["'ff'","'0xff'","255","Error"],ans:1},
{id:419,topic:"PY",level:"hard",q:"What is oct(8)?",opts:["'10'","'0o10'","8","Error"],ans:1},
{id:420,topic:"PY",level:"hard",q:"What is int('0b101', 0)?",opts:["0","5","'0b101'","Error"],ans:1},
{id:421,topic:"PY",level:"hard",q:"What is chr(65)?",opts:["'a'","'A'","65","Error"],ans:1},
{id:422,topic:"PY",level:"hard",q:"What is ord('A')?",opts:["65","97","'A'","Error"],ans:0},
{id:423,topic:"PY",level:"hard",q:"What does ascii('é') do?",opts:["é","\\xe9 escaped","Errors","Empty"],ans:1},
{id:424,topic:"PY",level:"hard",q:"Difference repr vs str on string?",opts:["Same","repr adds quotes/escapes; str raw","Reversed","No"],ans:1},
{id:425,topic:"PY",level:"hard",q:"What is generator.throw(exc)?",opts:["Errors","Throws exception into generator at yield point","Skip","Stop"],ans:1},
{id:426,topic:"PY",level:"hard",q:"What is a coroutine?",opts:["Iter","Function that can pause via yield/await","Class","Method"],ans:1},
{id:427,topic:"PY",level:"hard",q:"What is async for?",opts:["Same","Iterate async iterable in async fn","Sync","Error"],ans:1},
{id:428,topic:"PY",level:"hard",q:"What is async with?",opts:["Sync","Use async context manager","Sync","Error"],ans:1},
{id:429,topic:"PY",level:"hard",q:"What does asyncio.gather do?",opts:["Run async tasks concurrently and await all","Sequential","Errors","Cancel"],ans:0},
{id:430,topic:"PY",level:"hard",q:"What's a weak reference?",opts:["Bad","Reference that doesn't prevent GC (weakref)","Strong","Hidden"],ans:1},
{id:431,topic:"PY",level:"hard",q:"What's the use of __all__ in module?",opts:["Cache","Controls names exposed by 'from m import *'","Errors","Type"],ans:1},
{id:432,topic:"PY",level:"hard",q:"What is type() with 3 args?",opts:["Errors","Dynamically creates a class","Cast","Check"],ans:1},
{id:433,topic:"PY",level:"hard",q:"Default base class of all in Python 3?",opts:["object","Object","None","No base"],ans:0},
{id:434,topic:"PY",level:"hard",q:"What is callable(x)?",opts:["Run x","Returns True if x can be called like fn","Cast","Skip"],ans:1},
{id:435,topic:"PY",level:"hard",q:"What is the result of [].append(1)?",opts:["[1]","None (mutates)","Error","[]"],ans:1},
{id:436,topic:"PY",level:"hard",q:"What is the result of [1,2].extend([3,4])?",opts:["[1,2,3,4]","None (mutates to [1,2,3,4])","Errors","[3,4]"],ans:1},
{id:437,topic:"PY",level:"hard",q:"What does s.endswith(('a','b'))?",opts:["Errors","True if endswith 'a' OR 'b'","Both","No"],ans:1},
{id:438,topic:"PY",level:"hard",q:"How to check if all are equal in list?",opts:["len(set(l))==1","all(l)","unique(l)","l.all()"],ans:0},
{id:439,topic:"PY",level:"hard",q:"What is functools.partial?",opts:["Half","Pre-fills some args, returns new callable","Decorator","Cache"],ans:1},
{id:440,topic:"PY",level:"hard",q:"What does dict | dict2 do (3.9+)?",opts:["Errors","Merge dicts into new","Set or","Reverse"],ans:1},
{id:441,topic:"PY",level:"hard",q:"What does dict |= dict2 do?",opts:["No","In-place merge","Error","Replace"],ans:1},
{id:442,topic:"PY",level:"hard",q:"What's the use of pprint module?",opts:["Faster","Pretty print complex data","Old","Cache"],ans:1},
{id:443,topic:"PY",level:"hard",q:"What is statistics.mean?",opts:["Median","Arithmetic mean","Max","Min"],ans:1},
{id:444,topic:"PY",level:"hard",q:"What is statistics.median?",opts:["Mean","Median value","Mode","Range"],ans:1},
{id:445,topic:"PY",level:"hard",q:"What is statistics.stdev?",opts:["Var","Sample standard deviation","Range","Mean"],ans:1},
{id:446,topic:"PY",level:"hard",q:"How to remove all occurrences of x from list?",opts:["l.removeAll(x)","[i for i in l if i!=x]","l.clear(x)","l-=x"],ans:1},
{id:447,topic:"PY",level:"hard",q:"How to find common items between two lists?",opts:["set(a) & set(b)","a.intersect(b)","a&b","commonalists(a,b)"],ans:0},
{id:448,topic:"PY",level:"hard",q:"How to merge two sorted lists?",opts:["sorted(a+b)","heapq.merge(a,b)","Both work","Neither"],ans:2},
{id:449,topic:"PY",level:"hard",q:"What is the heapq module?",opts:["Sort","Min-heap (priority queue) via list","Stack","Hash"],ans:1},
{id:450,topic:"PY",level:"hard",q:"What does heapq.heappush do?",opts:["Append","Push value, maintain heap property","Sort","Pop"],ans:1}
];

// Merge into global POOL
if (typeof POOL !== "undefined") {
    POOL.HTML.push(...HTML_EXTRA);
    POOL.CSS.push(...CSS_EXTRA);
    POOL.JS.push(...JS_EXTRA);
    POOL.PY.push(...PY_EXTRA);
    console.log("[pool] loaded:",
        "HTML=" + POOL.HTML.length,
        "CSS="  + POOL.CSS.length,
        "JS="   + POOL.JS.length,
        "PY="   + POOL.PY.length,
        "TOTAL="+ (POOL.HTML.length + POOL.CSS.length + POOL.JS.length + POOL.PY.length));
}

})();
